
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model example_account
 * 
 */
export type example_account = Prisma.example_accountModel
/**
 * Model example_session
 * 
 */
export type example_session = Prisma.example_sessionModel
/**
 * Model example_user
 * 
 */
export type example_user = Prisma.example_userModel
/**
 * Model example_verification
 * 
 */
export type example_verification = Prisma.example_verificationModel
/**
 * Model interviews_tool_account
 * 
 */
export type interviews_tool_account = Prisma.interviews_tool_accountModel
/**
 * Model interviews_tool_company_details
 * 
 */
export type interviews_tool_company_details = Prisma.interviews_tool_company_detailsModel
/**
 * Model interviews_tool_hiring_process
 * 
 */
export type interviews_tool_hiring_process = Prisma.interviews_tool_hiring_processModel
/**
 * Model interviews_tool_interaction
 * 
 */
export type interviews_tool_interaction = Prisma.interviews_tool_interactionModel
/**
 * Model interviews_tool_interview
 * 
 */
export type interviews_tool_interview = Prisma.interviews_tool_interviewModel
/**
 * Model interviews_tool_session
 * 
 */
export type interviews_tool_session = Prisma.interviews_tool_sessionModel
/**
 * Model interviews_tool_user
 * 
 */
export type interviews_tool_user = Prisma.interviews_tool_userModel
/**
 * Model interviews_tool_verification
 * 
 */
export type interviews_tool_verification = Prisma.interviews_tool_verificationModel
/**
 * Model real_estate_broker_system_account
 * 
 */
export type real_estate_broker_system_account = Prisma.real_estate_broker_system_accountModel
/**
 * Model real_estate_broker_system_session
 * 
 */
export type real_estate_broker_system_session = Prisma.real_estate_broker_system_sessionModel
/**
 * Model real_estate_broker_system_user
 * 
 */
export type real_estate_broker_system_user = Prisma.real_estate_broker_system_userModel
/**
 * Model real_estate_broker_system_verification
 * 
 */
export type real_estate_broker_system_verification = Prisma.real_estate_broker_system_verificationModel
