
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type Enumhiring_process_statusFilter<$PrismaModel = never> = {
  equals?: $Enums.hiring_process_status | Prisma.Enumhiring_process_statusFieldRefInput<$PrismaModel>
  in?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  notIn?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumhiring_process_statusFilter<$PrismaModel> | $Enums.hiring_process_status
}

export type EnumcurrencyFilter<$PrismaModel = never> = {
  equals?: $Enums.currency | Prisma.EnumcurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumcurrencyFilter<$PrismaModel> | $Enums.currency
}

export type Enumsalary_rate_typeFilter<$PrismaModel = never> = {
  equals?: $Enums.salary_rate_type | Prisma.Enumsalary_rate_typeFieldRefInput<$PrismaModel>
  in?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  notIn?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumsalary_rate_typeFilter<$PrismaModel> | $Enums.salary_rate_type
}

export type Enumhiring_process_statusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.hiring_process_status | Prisma.Enumhiring_process_statusFieldRefInput<$PrismaModel>
  in?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  notIn?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumhiring_process_statusWithAggregatesFilter<$PrismaModel> | $Enums.hiring_process_status
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumhiring_process_statusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumhiring_process_statusFilter<$PrismaModel>
}

export type EnumcurrencyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.currency | Prisma.EnumcurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumcurrencyWithAggregatesFilter<$PrismaModel> | $Enums.currency
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumcurrencyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumcurrencyFilter<$PrismaModel>
}

export type Enumsalary_rate_typeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.salary_rate_type | Prisma.Enumsalary_rate_typeFieldRefInput<$PrismaModel>
  in?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  notIn?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumsalary_rate_typeWithAggregatesFilter<$PrismaModel> | $Enums.salary_rate_type
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumsalary_rate_typeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumsalary_rate_typeFilter<$PrismaModel>
}

export type Enuminteraction_typeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.interaction_type | Prisma.Enuminteraction_typeFieldRefInput<$PrismaModel> | null
  in?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnuminteraction_typeNullableFilter<$PrismaModel> | $Enums.interaction_type | null
}

export type Enuminteraction_typeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.interaction_type | Prisma.Enuminteraction_typeFieldRefInput<$PrismaModel> | null
  in?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnuminteraction_typeNullableWithAggregatesFilter<$PrismaModel> | $Enums.interaction_type | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnuminteraction_typeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnuminteraction_typeNullableFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumhiring_process_statusFilter<$PrismaModel = never> = {
  equals?: $Enums.hiring_process_status | Prisma.Enumhiring_process_statusFieldRefInput<$PrismaModel>
  in?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  notIn?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumhiring_process_statusFilter<$PrismaModel> | $Enums.hiring_process_status
}

export type NestedEnumcurrencyFilter<$PrismaModel = never> = {
  equals?: $Enums.currency | Prisma.EnumcurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumcurrencyFilter<$PrismaModel> | $Enums.currency
}

export type NestedEnumsalary_rate_typeFilter<$PrismaModel = never> = {
  equals?: $Enums.salary_rate_type | Prisma.Enumsalary_rate_typeFieldRefInput<$PrismaModel>
  in?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  notIn?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumsalary_rate_typeFilter<$PrismaModel> | $Enums.salary_rate_type
}

export type NestedEnumhiring_process_statusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.hiring_process_status | Prisma.Enumhiring_process_statusFieldRefInput<$PrismaModel>
  in?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  notIn?: $Enums.hiring_process_status[] | Prisma.ListEnumhiring_process_statusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumhiring_process_statusWithAggregatesFilter<$PrismaModel> | $Enums.hiring_process_status
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumhiring_process_statusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumhiring_process_statusFilter<$PrismaModel>
}

export type NestedEnumcurrencyWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.currency | Prisma.EnumcurrencyFieldRefInput<$PrismaModel>
  in?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  notIn?: $Enums.currency[] | Prisma.ListEnumcurrencyFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumcurrencyWithAggregatesFilter<$PrismaModel> | $Enums.currency
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumcurrencyFilter<$PrismaModel>
  _max?: Prisma.NestedEnumcurrencyFilter<$PrismaModel>
}

export type NestedEnumsalary_rate_typeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.salary_rate_type | Prisma.Enumsalary_rate_typeFieldRefInput<$PrismaModel>
  in?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  notIn?: $Enums.salary_rate_type[] | Prisma.ListEnumsalary_rate_typeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumsalary_rate_typeWithAggregatesFilter<$PrismaModel> | $Enums.salary_rate_type
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumsalary_rate_typeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumsalary_rate_typeFilter<$PrismaModel>
}

export type NestedEnuminteraction_typeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.interaction_type | Prisma.Enuminteraction_typeFieldRefInput<$PrismaModel> | null
  in?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnuminteraction_typeNullableFilter<$PrismaModel> | $Enums.interaction_type | null
}

export type NestedEnuminteraction_typeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.interaction_type | Prisma.Enuminteraction_typeFieldRefInput<$PrismaModel> | null
  in?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.interaction_type[] | Prisma.ListEnuminteraction_typeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnuminteraction_typeNullableWithAggregatesFilter<$PrismaModel> | $Enums.interaction_type | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnuminteraction_typeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnuminteraction_typeNullableFilter<$PrismaModel>
}


