
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  example_account: 'example_account',
  example_session: 'example_session',
  example_user: 'example_user',
  example_verification: 'example_verification',
  interviews_tool_account: 'interviews_tool_account',
  interviews_tool_company_details: 'interviews_tool_company_details',
  interviews_tool_hiring_process: 'interviews_tool_hiring_process',
  interviews_tool_interaction: 'interviews_tool_interaction',
  interviews_tool_interview: 'interviews_tool_interview',
  interviews_tool_session: 'interviews_tool_session',
  interviews_tool_user: 'interviews_tool_user',
  interviews_tool_verification: 'interviews_tool_verification',
  real_estate_broker_system_account: 'real_estate_broker_system_account',
  real_estate_broker_system_session: 'real_estate_broker_system_session',
  real_estate_broker_system_user: 'real_estate_broker_system_user',
  real_estate_broker_system_verification: 'real_estate_broker_system_verification'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "example_account" | "example_session" | "example_user" | "example_verification" | "interviews_tool_account" | "interviews_tool_company_details" | "interviews_tool_hiring_process" | "interviews_tool_interaction" | "interviews_tool_interview" | "interviews_tool_session" | "interviews_tool_user" | "interviews_tool_verification" | "real_estate_broker_system_account" | "real_estate_broker_system_session" | "real_estate_broker_system_user" | "real_estate_broker_system_verification"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    example_account: {
      payload: Prisma.$example_accountPayload<ExtArgs>
      fields: Prisma.example_accountFieldRefs
      operations: {
        findUnique: {
          args: Prisma.example_accountFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.example_accountFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>
        }
        findFirst: {
          args: Prisma.example_accountFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.example_accountFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>
        }
        findMany: {
          args: Prisma.example_accountFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>[]
        }
        create: {
          args: Prisma.example_accountCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>
        }
        createMany: {
          args: Prisma.example_accountCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.example_accountCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>[]
        }
        delete: {
          args: Prisma.example_accountDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>
        }
        update: {
          args: Prisma.example_accountUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>
        }
        deleteMany: {
          args: Prisma.example_accountDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.example_accountUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.example_accountUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>[]
        }
        upsert: {
          args: Prisma.example_accountUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_accountPayload>
        }
        aggregate: {
          args: Prisma.Example_accountAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExample_account>
        }
        groupBy: {
          args: Prisma.example_accountGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_accountGroupByOutputType>[]
        }
        count: {
          args: Prisma.example_accountCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_accountCountAggregateOutputType> | number
        }
      }
    }
    example_session: {
      payload: Prisma.$example_sessionPayload<ExtArgs>
      fields: Prisma.example_sessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.example_sessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.example_sessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>
        }
        findFirst: {
          args: Prisma.example_sessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.example_sessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>
        }
        findMany: {
          args: Prisma.example_sessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>[]
        }
        create: {
          args: Prisma.example_sessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>
        }
        createMany: {
          args: Prisma.example_sessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.example_sessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>[]
        }
        delete: {
          args: Prisma.example_sessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>
        }
        update: {
          args: Prisma.example_sessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>
        }
        deleteMany: {
          args: Prisma.example_sessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.example_sessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.example_sessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>[]
        }
        upsert: {
          args: Prisma.example_sessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_sessionPayload>
        }
        aggregate: {
          args: Prisma.Example_sessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExample_session>
        }
        groupBy: {
          args: Prisma.example_sessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_sessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.example_sessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_sessionCountAggregateOutputType> | number
        }
      }
    }
    example_user: {
      payload: Prisma.$example_userPayload<ExtArgs>
      fields: Prisma.example_userFieldRefs
      operations: {
        findUnique: {
          args: Prisma.example_userFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.example_userFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>
        }
        findFirst: {
          args: Prisma.example_userFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.example_userFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>
        }
        findMany: {
          args: Prisma.example_userFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>[]
        }
        create: {
          args: Prisma.example_userCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>
        }
        createMany: {
          args: Prisma.example_userCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.example_userCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>[]
        }
        delete: {
          args: Prisma.example_userDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>
        }
        update: {
          args: Prisma.example_userUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>
        }
        deleteMany: {
          args: Prisma.example_userDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.example_userUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.example_userUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>[]
        }
        upsert: {
          args: Prisma.example_userUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_userPayload>
        }
        aggregate: {
          args: Prisma.Example_userAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExample_user>
        }
        groupBy: {
          args: Prisma.example_userGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_userGroupByOutputType>[]
        }
        count: {
          args: Prisma.example_userCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_userCountAggregateOutputType> | number
        }
      }
    }
    example_verification: {
      payload: Prisma.$example_verificationPayload<ExtArgs>
      fields: Prisma.example_verificationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.example_verificationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.example_verificationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>
        }
        findFirst: {
          args: Prisma.example_verificationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.example_verificationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>
        }
        findMany: {
          args: Prisma.example_verificationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>[]
        }
        create: {
          args: Prisma.example_verificationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>
        }
        createMany: {
          args: Prisma.example_verificationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.example_verificationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>[]
        }
        delete: {
          args: Prisma.example_verificationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>
        }
        update: {
          args: Prisma.example_verificationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>
        }
        deleteMany: {
          args: Prisma.example_verificationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.example_verificationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.example_verificationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>[]
        }
        upsert: {
          args: Prisma.example_verificationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$example_verificationPayload>
        }
        aggregate: {
          args: Prisma.Example_verificationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExample_verification>
        }
        groupBy: {
          args: Prisma.example_verificationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_verificationGroupByOutputType>[]
        }
        count: {
          args: Prisma.example_verificationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Example_verificationCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_account: {
      payload: Prisma.$interviews_tool_accountPayload<ExtArgs>
      fields: Prisma.interviews_tool_accountFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_accountFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_accountFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_accountFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_accountFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_accountFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_accountCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_accountCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_accountCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_accountDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>
        }
        update: {
          args: Prisma.interviews_tool_accountUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_accountDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_accountUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_accountUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_accountUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_accountPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_accountAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_account>
        }
        groupBy: {
          args: Prisma.interviews_tool_accountGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_accountGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_accountCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_accountCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_company_details: {
      payload: Prisma.$interviews_tool_company_detailsPayload<ExtArgs>
      fields: Prisma.interviews_tool_company_detailsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_company_detailsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_company_detailsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_company_detailsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_company_detailsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_company_detailsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_company_detailsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_company_detailsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_company_detailsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_company_detailsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>
        }
        update: {
          args: Prisma.interviews_tool_company_detailsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_company_detailsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_company_detailsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_company_detailsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_company_detailsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_company_detailsPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_company_detailsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_company_details>
        }
        groupBy: {
          args: Prisma.interviews_tool_company_detailsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_company_detailsGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_company_detailsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_company_detailsCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_hiring_process: {
      payload: Prisma.$interviews_tool_hiring_processPayload<ExtArgs>
      fields: Prisma.interviews_tool_hiring_processFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_hiring_processFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_hiring_processFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_hiring_processFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_hiring_processFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_hiring_processFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_hiring_processCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_hiring_processCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_hiring_processCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_hiring_processDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>
        }
        update: {
          args: Prisma.interviews_tool_hiring_processUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_hiring_processDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_hiring_processUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_hiring_processUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_hiring_processUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_hiring_processPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_hiring_processAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_hiring_process>
        }
        groupBy: {
          args: Prisma.interviews_tool_hiring_processGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_hiring_processGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_hiring_processCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_hiring_processCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_interaction: {
      payload: Prisma.$interviews_tool_interactionPayload<ExtArgs>
      fields: Prisma.interviews_tool_interactionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_interactionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_interactionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_interactionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_interactionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_interactionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_interactionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_interactionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_interactionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_interactionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>
        }
        update: {
          args: Prisma.interviews_tool_interactionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_interactionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_interactionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_interactionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_interactionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interactionPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_interactionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_interaction>
        }
        groupBy: {
          args: Prisma.interviews_tool_interactionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_interactionGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_interactionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_interactionCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_interview: {
      payload: Prisma.$interviews_tool_interviewPayload<ExtArgs>
      fields: Prisma.interviews_tool_interviewFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_interviewFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_interviewFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_interviewFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_interviewFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_interviewFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_interviewCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_interviewCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_interviewCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_interviewDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>
        }
        update: {
          args: Prisma.interviews_tool_interviewUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_interviewDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_interviewUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_interviewUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_interviewUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_interviewPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_interviewAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_interview>
        }
        groupBy: {
          args: Prisma.interviews_tool_interviewGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_interviewGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_interviewCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_interviewCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_session: {
      payload: Prisma.$interviews_tool_sessionPayload<ExtArgs>
      fields: Prisma.interviews_tool_sessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_sessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_sessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_sessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_sessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_sessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_sessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_sessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_sessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_sessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>
        }
        update: {
          args: Prisma.interviews_tool_sessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_sessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_sessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_sessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_sessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_sessionPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_sessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_session>
        }
        groupBy: {
          args: Prisma.interviews_tool_sessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_sessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_sessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_sessionCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_user: {
      payload: Prisma.$interviews_tool_userPayload<ExtArgs>
      fields: Prisma.interviews_tool_userFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_userFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_userFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_userFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_userFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_userFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_userCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_userCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_userCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_userDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>
        }
        update: {
          args: Prisma.interviews_tool_userUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_userDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_userUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_userUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_userUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_userPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_userAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_user>
        }
        groupBy: {
          args: Prisma.interviews_tool_userGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_userGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_userCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_userCountAggregateOutputType> | number
        }
      }
    }
    interviews_tool_verification: {
      payload: Prisma.$interviews_tool_verificationPayload<ExtArgs>
      fields: Prisma.interviews_tool_verificationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.interviews_tool_verificationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.interviews_tool_verificationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>
        }
        findFirst: {
          args: Prisma.interviews_tool_verificationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.interviews_tool_verificationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>
        }
        findMany: {
          args: Prisma.interviews_tool_verificationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>[]
        }
        create: {
          args: Prisma.interviews_tool_verificationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>
        }
        createMany: {
          args: Prisma.interviews_tool_verificationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.interviews_tool_verificationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>[]
        }
        delete: {
          args: Prisma.interviews_tool_verificationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>
        }
        update: {
          args: Prisma.interviews_tool_verificationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>
        }
        deleteMany: {
          args: Prisma.interviews_tool_verificationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.interviews_tool_verificationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.interviews_tool_verificationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>[]
        }
        upsert: {
          args: Prisma.interviews_tool_verificationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$interviews_tool_verificationPayload>
        }
        aggregate: {
          args: Prisma.Interviews_tool_verificationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInterviews_tool_verification>
        }
        groupBy: {
          args: Prisma.interviews_tool_verificationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_verificationGroupByOutputType>[]
        }
        count: {
          args: Prisma.interviews_tool_verificationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Interviews_tool_verificationCountAggregateOutputType> | number
        }
      }
    }
    real_estate_broker_system_account: {
      payload: Prisma.$real_estate_broker_system_accountPayload<ExtArgs>
      fields: Prisma.real_estate_broker_system_accountFieldRefs
      operations: {
        findUnique: {
          args: Prisma.real_estate_broker_system_accountFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.real_estate_broker_system_accountFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>
        }
        findFirst: {
          args: Prisma.real_estate_broker_system_accountFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.real_estate_broker_system_accountFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>
        }
        findMany: {
          args: Prisma.real_estate_broker_system_accountFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>[]
        }
        create: {
          args: Prisma.real_estate_broker_system_accountCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>
        }
        createMany: {
          args: Prisma.real_estate_broker_system_accountCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.real_estate_broker_system_accountCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>[]
        }
        delete: {
          args: Prisma.real_estate_broker_system_accountDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>
        }
        update: {
          args: Prisma.real_estate_broker_system_accountUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>
        }
        deleteMany: {
          args: Prisma.real_estate_broker_system_accountDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.real_estate_broker_system_accountUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.real_estate_broker_system_accountUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>[]
        }
        upsert: {
          args: Prisma.real_estate_broker_system_accountUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_accountPayload>
        }
        aggregate: {
          args: Prisma.Real_estate_broker_system_accountAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReal_estate_broker_system_account>
        }
        groupBy: {
          args: Prisma.real_estate_broker_system_accountGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_accountGroupByOutputType>[]
        }
        count: {
          args: Prisma.real_estate_broker_system_accountCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_accountCountAggregateOutputType> | number
        }
      }
    }
    real_estate_broker_system_session: {
      payload: Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>
      fields: Prisma.real_estate_broker_system_sessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.real_estate_broker_system_sessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.real_estate_broker_system_sessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>
        }
        findFirst: {
          args: Prisma.real_estate_broker_system_sessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.real_estate_broker_system_sessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>
        }
        findMany: {
          args: Prisma.real_estate_broker_system_sessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>[]
        }
        create: {
          args: Prisma.real_estate_broker_system_sessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>
        }
        createMany: {
          args: Prisma.real_estate_broker_system_sessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.real_estate_broker_system_sessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>[]
        }
        delete: {
          args: Prisma.real_estate_broker_system_sessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>
        }
        update: {
          args: Prisma.real_estate_broker_system_sessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>
        }
        deleteMany: {
          args: Prisma.real_estate_broker_system_sessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.real_estate_broker_system_sessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.real_estate_broker_system_sessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>[]
        }
        upsert: {
          args: Prisma.real_estate_broker_system_sessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_sessionPayload>
        }
        aggregate: {
          args: Prisma.Real_estate_broker_system_sessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReal_estate_broker_system_session>
        }
        groupBy: {
          args: Prisma.real_estate_broker_system_sessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_sessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.real_estate_broker_system_sessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_sessionCountAggregateOutputType> | number
        }
      }
    }
    real_estate_broker_system_user: {
      payload: Prisma.$real_estate_broker_system_userPayload<ExtArgs>
      fields: Prisma.real_estate_broker_system_userFieldRefs
      operations: {
        findUnique: {
          args: Prisma.real_estate_broker_system_userFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.real_estate_broker_system_userFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>
        }
        findFirst: {
          args: Prisma.real_estate_broker_system_userFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.real_estate_broker_system_userFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>
        }
        findMany: {
          args: Prisma.real_estate_broker_system_userFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>[]
        }
        create: {
          args: Prisma.real_estate_broker_system_userCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>
        }
        createMany: {
          args: Prisma.real_estate_broker_system_userCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.real_estate_broker_system_userCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>[]
        }
        delete: {
          args: Prisma.real_estate_broker_system_userDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>
        }
        update: {
          args: Prisma.real_estate_broker_system_userUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>
        }
        deleteMany: {
          args: Prisma.real_estate_broker_system_userDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.real_estate_broker_system_userUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.real_estate_broker_system_userUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>[]
        }
        upsert: {
          args: Prisma.real_estate_broker_system_userUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_userPayload>
        }
        aggregate: {
          args: Prisma.Real_estate_broker_system_userAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReal_estate_broker_system_user>
        }
        groupBy: {
          args: Prisma.real_estate_broker_system_userGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_userGroupByOutputType>[]
        }
        count: {
          args: Prisma.real_estate_broker_system_userCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_userCountAggregateOutputType> | number
        }
      }
    }
    real_estate_broker_system_verification: {
      payload: Prisma.$real_estate_broker_system_verificationPayload<ExtArgs>
      fields: Prisma.real_estate_broker_system_verificationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.real_estate_broker_system_verificationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.real_estate_broker_system_verificationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>
        }
        findFirst: {
          args: Prisma.real_estate_broker_system_verificationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.real_estate_broker_system_verificationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>
        }
        findMany: {
          args: Prisma.real_estate_broker_system_verificationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>[]
        }
        create: {
          args: Prisma.real_estate_broker_system_verificationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>
        }
        createMany: {
          args: Prisma.real_estate_broker_system_verificationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.real_estate_broker_system_verificationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>[]
        }
        delete: {
          args: Prisma.real_estate_broker_system_verificationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>
        }
        update: {
          args: Prisma.real_estate_broker_system_verificationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>
        }
        deleteMany: {
          args: Prisma.real_estate_broker_system_verificationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.real_estate_broker_system_verificationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.real_estate_broker_system_verificationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>[]
        }
        upsert: {
          args: Prisma.real_estate_broker_system_verificationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$real_estate_broker_system_verificationPayload>
        }
        aggregate: {
          args: Prisma.Real_estate_broker_system_verificationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReal_estate_broker_system_verification>
        }
        groupBy: {
          args: Prisma.real_estate_broker_system_verificationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_verificationGroupByOutputType>[]
        }
        count: {
          args: Prisma.real_estate_broker_system_verificationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Real_estate_broker_system_verificationCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Example_accountScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  provider_id: 'provider_id',
  user_id: 'user_id',
  access_token: 'access_token',
  refresh_token: 'refresh_token',
  id_token: 'id_token',
  access_token_expires_at: 'access_token_expires_at',
  refresh_token_expires_at: 'refresh_token_expires_at',
  scope: 'scope',
  password: 'password',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Example_accountScalarFieldEnum = (typeof Example_accountScalarFieldEnum)[keyof typeof Example_accountScalarFieldEnum]


export const Example_sessionScalarFieldEnum = {
  id: 'id',
  expires_at: 'expires_at',
  token: 'token',
  created_at: 'created_at',
  updated_at: 'updated_at',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  user_id: 'user_id'
} as const

export type Example_sessionScalarFieldEnum = (typeof Example_sessionScalarFieldEnum)[keyof typeof Example_sessionScalarFieldEnum]


export const Example_userScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  email_verified: 'email_verified',
  image: 'image',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Example_userScalarFieldEnum = (typeof Example_userScalarFieldEnum)[keyof typeof Example_userScalarFieldEnum]


export const Example_verificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Example_verificationScalarFieldEnum = (typeof Example_verificationScalarFieldEnum)[keyof typeof Example_verificationScalarFieldEnum]


export const Interviews_tool_accountScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  provider_id: 'provider_id',
  user_id: 'user_id',
  access_token: 'access_token',
  refresh_token: 'refresh_token',
  id_token: 'id_token',
  access_token_expires_at: 'access_token_expires_at',
  refresh_token_expires_at: 'refresh_token_expires_at',
  scope: 'scope',
  password: 'password',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_accountScalarFieldEnum = (typeof Interviews_tool_accountScalarFieldEnum)[keyof typeof Interviews_tool_accountScalarFieldEnum]


export const Interviews_tool_company_detailsScalarFieldEnum = {
  id: 'id',
  hiring_process_id: 'hiring_process_id',
  website: 'website',
  location: 'location',
  benefits: 'benefits',
  contacted_via: 'contacted_via',
  contact_person: 'contact_person',
  interview_steps: 'interview_steps',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type Interviews_tool_company_detailsScalarFieldEnum = (typeof Interviews_tool_company_detailsScalarFieldEnum)[keyof typeof Interviews_tool_company_detailsScalarFieldEnum]


export const Interviews_tool_hiring_processScalarFieldEnum = {
  id: 'id',
  company_name: 'company_name',
  status: 'status',
  salary: 'salary',
  currency: 'currency',
  created_at: 'created_at',
  updated_at: 'updated_at',
  user_id: 'user_id',
  job_title: 'job_title',
  deleted_at: 'deleted_at',
  salary_rate_type: 'salary_rate_type'
} as const

export type Interviews_tool_hiring_processScalarFieldEnum = (typeof Interviews_tool_hiring_processScalarFieldEnum)[keyof typeof Interviews_tool_hiring_processScalarFieldEnum]


export const Interviews_tool_interactionScalarFieldEnum = {
  id: 'id',
  hiring_process_id: 'hiring_process_id',
  title: 'title',
  content: 'content',
  type: 'type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type Interviews_tool_interactionScalarFieldEnum = (typeof Interviews_tool_interactionScalarFieldEnum)[keyof typeof Interviews_tool_interactionScalarFieldEnum]


export const Interviews_tool_interviewScalarFieldEnum = {
  id: 'id',
  hiring_process_id: 'hiring_process_id',
  type: 'type',
  scheduled_at: 'scheduled_at',
  status: 'status',
  notes: 'notes',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_interviewScalarFieldEnum = (typeof Interviews_tool_interviewScalarFieldEnum)[keyof typeof Interviews_tool_interviewScalarFieldEnum]


export const Interviews_tool_sessionScalarFieldEnum = {
  id: 'id',
  expires_at: 'expires_at',
  token: 'token',
  created_at: 'created_at',
  updated_at: 'updated_at',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  user_id: 'user_id'
} as const

export type Interviews_tool_sessionScalarFieldEnum = (typeof Interviews_tool_sessionScalarFieldEnum)[keyof typeof Interviews_tool_sessionScalarFieldEnum]


export const Interviews_tool_userScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  email_verified: 'email_verified',
  image: 'image',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_userScalarFieldEnum = (typeof Interviews_tool_userScalarFieldEnum)[keyof typeof Interviews_tool_userScalarFieldEnum]


export const Interviews_tool_verificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_verificationScalarFieldEnum = (typeof Interviews_tool_verificationScalarFieldEnum)[keyof typeof Interviews_tool_verificationScalarFieldEnum]


export const Real_estate_broker_system_accountScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  provider_id: 'provider_id',
  user_id: 'user_id',
  access_token: 'access_token',
  refresh_token: 'refresh_token',
  id_token: 'id_token',
  access_token_expires_at: 'access_token_expires_at',
  refresh_token_expires_at: 'refresh_token_expires_at',
  scope: 'scope',
  password: 'password',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Real_estate_broker_system_accountScalarFieldEnum = (typeof Real_estate_broker_system_accountScalarFieldEnum)[keyof typeof Real_estate_broker_system_accountScalarFieldEnum]


export const Real_estate_broker_system_sessionScalarFieldEnum = {
  id: 'id',
  expires_at: 'expires_at',
  token: 'token',
  created_at: 'created_at',
  updated_at: 'updated_at',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  user_id: 'user_id'
} as const

export type Real_estate_broker_system_sessionScalarFieldEnum = (typeof Real_estate_broker_system_sessionScalarFieldEnum)[keyof typeof Real_estate_broker_system_sessionScalarFieldEnum]


export const Real_estate_broker_system_userScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  email_verified: 'email_verified',
  image: 'image',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Real_estate_broker_system_userScalarFieldEnum = (typeof Real_estate_broker_system_userScalarFieldEnum)[keyof typeof Real_estate_broker_system_userScalarFieldEnum]


export const Real_estate_broker_system_verificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Real_estate_broker_system_verificationScalarFieldEnum = (typeof Real_estate_broker_system_verificationScalarFieldEnum)[keyof typeof Real_estate_broker_system_verificationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'hiring_process_status'
 */
export type Enumhiring_process_statusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'hiring_process_status'>
    


/**
 * Reference to a field of type 'hiring_process_status[]'
 */
export type ListEnumhiring_process_statusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'hiring_process_status[]'>
    


/**
 * Reference to a field of type 'currency'
 */
export type EnumcurrencyFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'currency'>
    


/**
 * Reference to a field of type 'currency[]'
 */
export type ListEnumcurrencyFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'currency[]'>
    


/**
 * Reference to a field of type 'salary_rate_type'
 */
export type Enumsalary_rate_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'salary_rate_type'>
    


/**
 * Reference to a field of type 'salary_rate_type[]'
 */
export type ListEnumsalary_rate_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'salary_rate_type[]'>
    


/**
 * Reference to a field of type 'interaction_type'
 */
export type Enuminteraction_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'interaction_type'>
    


/**
 * Reference to a field of type 'interaction_type[]'
 */
export type ListEnuminteraction_typeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'interaction_type[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  example_account?: Prisma.example_accountOmit
  example_session?: Prisma.example_sessionOmit
  example_user?: Prisma.example_userOmit
  example_verification?: Prisma.example_verificationOmit
  interviews_tool_account?: Prisma.interviews_tool_accountOmit
  interviews_tool_company_details?: Prisma.interviews_tool_company_detailsOmit
  interviews_tool_hiring_process?: Prisma.interviews_tool_hiring_processOmit
  interviews_tool_interaction?: Prisma.interviews_tool_interactionOmit
  interviews_tool_interview?: Prisma.interviews_tool_interviewOmit
  interviews_tool_session?: Prisma.interviews_tool_sessionOmit
  interviews_tool_user?: Prisma.interviews_tool_userOmit
  interviews_tool_verification?: Prisma.interviews_tool_verificationOmit
  real_estate_broker_system_account?: Prisma.real_estate_broker_system_accountOmit
  real_estate_broker_system_session?: Prisma.real_estate_broker_system_sessionOmit
  real_estate_broker_system_user?: Prisma.real_estate_broker_system_userOmit
  real_estate_broker_system_verification?: Prisma.real_estate_broker_system_verificationOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

