
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  example_account: 'example_account',
  example_session: 'example_session',
  example_user: 'example_user',
  example_verification: 'example_verification',
  interviews_tool_account: 'interviews_tool_account',
  interviews_tool_company_details: 'interviews_tool_company_details',
  interviews_tool_hiring_process: 'interviews_tool_hiring_process',
  interviews_tool_interaction: 'interviews_tool_interaction',
  interviews_tool_interview: 'interviews_tool_interview',
  interviews_tool_session: 'interviews_tool_session',
  interviews_tool_user: 'interviews_tool_user',
  interviews_tool_verification: 'interviews_tool_verification',
  real_estate_broker_system_account: 'real_estate_broker_system_account',
  real_estate_broker_system_session: 'real_estate_broker_system_session',
  real_estate_broker_system_user: 'real_estate_broker_system_user',
  real_estate_broker_system_verification: 'real_estate_broker_system_verification'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Example_accountScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  provider_id: 'provider_id',
  user_id: 'user_id',
  access_token: 'access_token',
  refresh_token: 'refresh_token',
  id_token: 'id_token',
  access_token_expires_at: 'access_token_expires_at',
  refresh_token_expires_at: 'refresh_token_expires_at',
  scope: 'scope',
  password: 'password',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Example_accountScalarFieldEnum = (typeof Example_accountScalarFieldEnum)[keyof typeof Example_accountScalarFieldEnum]


export const Example_sessionScalarFieldEnum = {
  id: 'id',
  expires_at: 'expires_at',
  token: 'token',
  created_at: 'created_at',
  updated_at: 'updated_at',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  user_id: 'user_id'
} as const

export type Example_sessionScalarFieldEnum = (typeof Example_sessionScalarFieldEnum)[keyof typeof Example_sessionScalarFieldEnum]


export const Example_userScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  email_verified: 'email_verified',
  image: 'image',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Example_userScalarFieldEnum = (typeof Example_userScalarFieldEnum)[keyof typeof Example_userScalarFieldEnum]


export const Example_verificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Example_verificationScalarFieldEnum = (typeof Example_verificationScalarFieldEnum)[keyof typeof Example_verificationScalarFieldEnum]


export const Interviews_tool_accountScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  provider_id: 'provider_id',
  user_id: 'user_id',
  access_token: 'access_token',
  refresh_token: 'refresh_token',
  id_token: 'id_token',
  access_token_expires_at: 'access_token_expires_at',
  refresh_token_expires_at: 'refresh_token_expires_at',
  scope: 'scope',
  password: 'password',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_accountScalarFieldEnum = (typeof Interviews_tool_accountScalarFieldEnum)[keyof typeof Interviews_tool_accountScalarFieldEnum]


export const Interviews_tool_company_detailsScalarFieldEnum = {
  id: 'id',
  hiring_process_id: 'hiring_process_id',
  website: 'website',
  location: 'location',
  benefits: 'benefits',
  contacted_via: 'contacted_via',
  contact_person: 'contact_person',
  interview_steps: 'interview_steps',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type Interviews_tool_company_detailsScalarFieldEnum = (typeof Interviews_tool_company_detailsScalarFieldEnum)[keyof typeof Interviews_tool_company_detailsScalarFieldEnum]


export const Interviews_tool_hiring_processScalarFieldEnum = {
  id: 'id',
  company_name: 'company_name',
  status: 'status',
  salary: 'salary',
  currency: 'currency',
  created_at: 'created_at',
  updated_at: 'updated_at',
  user_id: 'user_id',
  job_title: 'job_title',
  deleted_at: 'deleted_at',
  salary_rate_type: 'salary_rate_type'
} as const

export type Interviews_tool_hiring_processScalarFieldEnum = (typeof Interviews_tool_hiring_processScalarFieldEnum)[keyof typeof Interviews_tool_hiring_processScalarFieldEnum]


export const Interviews_tool_interactionScalarFieldEnum = {
  id: 'id',
  hiring_process_id: 'hiring_process_id',
  title: 'title',
  content: 'content',
  type: 'type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type Interviews_tool_interactionScalarFieldEnum = (typeof Interviews_tool_interactionScalarFieldEnum)[keyof typeof Interviews_tool_interactionScalarFieldEnum]


export const Interviews_tool_interviewScalarFieldEnum = {
  id: 'id',
  hiring_process_id: 'hiring_process_id',
  type: 'type',
  scheduled_at: 'scheduled_at',
  status: 'status',
  notes: 'notes',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_interviewScalarFieldEnum = (typeof Interviews_tool_interviewScalarFieldEnum)[keyof typeof Interviews_tool_interviewScalarFieldEnum]


export const Interviews_tool_sessionScalarFieldEnum = {
  id: 'id',
  expires_at: 'expires_at',
  token: 'token',
  created_at: 'created_at',
  updated_at: 'updated_at',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  user_id: 'user_id'
} as const

export type Interviews_tool_sessionScalarFieldEnum = (typeof Interviews_tool_sessionScalarFieldEnum)[keyof typeof Interviews_tool_sessionScalarFieldEnum]


export const Interviews_tool_userScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  email_verified: 'email_verified',
  image: 'image',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_userScalarFieldEnum = (typeof Interviews_tool_userScalarFieldEnum)[keyof typeof Interviews_tool_userScalarFieldEnum]


export const Interviews_tool_verificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Interviews_tool_verificationScalarFieldEnum = (typeof Interviews_tool_verificationScalarFieldEnum)[keyof typeof Interviews_tool_verificationScalarFieldEnum]


export const Real_estate_broker_system_accountScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  provider_id: 'provider_id',
  user_id: 'user_id',
  access_token: 'access_token',
  refresh_token: 'refresh_token',
  id_token: 'id_token',
  access_token_expires_at: 'access_token_expires_at',
  refresh_token_expires_at: 'refresh_token_expires_at',
  scope: 'scope',
  password: 'password',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Real_estate_broker_system_accountScalarFieldEnum = (typeof Real_estate_broker_system_accountScalarFieldEnum)[keyof typeof Real_estate_broker_system_accountScalarFieldEnum]


export const Real_estate_broker_system_sessionScalarFieldEnum = {
  id: 'id',
  expires_at: 'expires_at',
  token: 'token',
  created_at: 'created_at',
  updated_at: 'updated_at',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  user_id: 'user_id'
} as const

export type Real_estate_broker_system_sessionScalarFieldEnum = (typeof Real_estate_broker_system_sessionScalarFieldEnum)[keyof typeof Real_estate_broker_system_sessionScalarFieldEnum]


export const Real_estate_broker_system_userScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  email_verified: 'email_verified',
  image: 'image',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Real_estate_broker_system_userScalarFieldEnum = (typeof Real_estate_broker_system_userScalarFieldEnum)[keyof typeof Real_estate_broker_system_userScalarFieldEnum]


export const Real_estate_broker_system_verificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Real_estate_broker_system_verificationScalarFieldEnum = (typeof Real_estate_broker_system_verificationScalarFieldEnum)[keyof typeof Real_estate_broker_system_verificationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

