
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `example_user` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model example_user
 * 
 */
export type example_userModel = runtime.Types.Result.DefaultSelection<Prisma.$example_userPayload>

export type AggregateExample_user = {
  _count: Example_userCountAggregateOutputType | null
  _min: Example_userMinAggregateOutputType | null
  _max: Example_userMaxAggregateOutputType | null
}

export type Example_userMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  email_verified: boolean | null
  image: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Example_userMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  email_verified: boolean | null
  image: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Example_userCountAggregateOutputType = {
  id: number
  name: number
  email: number
  email_verified: number
  image: number
  created_at: number
  updated_at: number
  _all: number
}


export type Example_userMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  email_verified?: true
  image?: true
  created_at?: true
  updated_at?: true
}

export type Example_userMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  email_verified?: true
  image?: true
  created_at?: true
  updated_at?: true
}

export type Example_userCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  email_verified?: true
  image?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Example_userAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which example_user to aggregate.
   */
  where?: Prisma.example_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of example_users to fetch.
   */
  orderBy?: Prisma.example_userOrderByWithRelationInput | Prisma.example_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.example_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` example_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` example_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned example_users
  **/
  _count?: true | Example_userCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Example_userMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Example_userMaxAggregateInputType
}

export type GetExample_userAggregateType<T extends Example_userAggregateArgs> = {
      [P in keyof T & keyof AggregateExample_user]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExample_user[P]>
    : Prisma.GetScalarType<T[P], AggregateExample_user[P]>
}




export type example_userGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.example_userWhereInput
  orderBy?: Prisma.example_userOrderByWithAggregationInput | Prisma.example_userOrderByWithAggregationInput[]
  by: Prisma.Example_userScalarFieldEnum[] | Prisma.Example_userScalarFieldEnum
  having?: Prisma.example_userScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Example_userCountAggregateInputType | true
  _min?: Example_userMinAggregateInputType
  _max?: Example_userMaxAggregateInputType
}

export type Example_userGroupByOutputType = {
  id: string
  name: string
  email: string
  email_verified: boolean
  image: string | null
  created_at: Date
  updated_at: Date
  _count: Example_userCountAggregateOutputType | null
  _min: Example_userMinAggregateOutputType | null
  _max: Example_userMaxAggregateOutputType | null
}

export type GetExample_userGroupByPayload<T extends example_userGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Example_userGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Example_userGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Example_userGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Example_userGroupByOutputType[P]>
      }
    >
  >



export type example_userWhereInput = {
  AND?: Prisma.example_userWhereInput | Prisma.example_userWhereInput[]
  OR?: Prisma.example_userWhereInput[]
  NOT?: Prisma.example_userWhereInput | Prisma.example_userWhereInput[]
  id?: Prisma.StringFilter<"example_user"> | string
  name?: Prisma.StringFilter<"example_user"> | string
  email?: Prisma.StringFilter<"example_user"> | string
  email_verified?: Prisma.BoolFilter<"example_user"> | boolean
  image?: Prisma.StringNullableFilter<"example_user"> | string | null
  created_at?: Prisma.DateTimeFilter<"example_user"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"example_user"> | Date | string
  example_account?: Prisma.Example_accountListRelationFilter
  example_session?: Prisma.Example_sessionListRelationFilter
}

export type example_userOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  example_account?: Prisma.example_accountOrderByRelationAggregateInput
  example_session?: Prisma.example_sessionOrderByRelationAggregateInput
}

export type example_userWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.example_userWhereInput | Prisma.example_userWhereInput[]
  OR?: Prisma.example_userWhereInput[]
  NOT?: Prisma.example_userWhereInput | Prisma.example_userWhereInput[]
  name?: Prisma.StringFilter<"example_user"> | string
  email_verified?: Prisma.BoolFilter<"example_user"> | boolean
  image?: Prisma.StringNullableFilter<"example_user"> | string | null
  created_at?: Prisma.DateTimeFilter<"example_user"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"example_user"> | Date | string
  example_account?: Prisma.Example_accountListRelationFilter
  example_session?: Prisma.Example_sessionListRelationFilter
}, "id" | "email">

export type example_userOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.example_userCountOrderByAggregateInput
  _max?: Prisma.example_userMaxOrderByAggregateInput
  _min?: Prisma.example_userMinOrderByAggregateInput
}

export type example_userScalarWhereWithAggregatesInput = {
  AND?: Prisma.example_userScalarWhereWithAggregatesInput | Prisma.example_userScalarWhereWithAggregatesInput[]
  OR?: Prisma.example_userScalarWhereWithAggregatesInput[]
  NOT?: Prisma.example_userScalarWhereWithAggregatesInput | Prisma.example_userScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"example_user"> | string
  name?: Prisma.StringWithAggregatesFilter<"example_user"> | string
  email?: Prisma.StringWithAggregatesFilter<"example_user"> | string
  email_verified?: Prisma.BoolWithAggregatesFilter<"example_user"> | boolean
  image?: Prisma.StringNullableWithAggregatesFilter<"example_user"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"example_user"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"example_user"> | Date | string
}

export type example_userCreateInput = {
  id: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  example_account?: Prisma.example_accountCreateNestedManyWithoutExample_userInput
  example_session?: Prisma.example_sessionCreateNestedManyWithoutExample_userInput
}

export type example_userUncheckedCreateInput = {
  id: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  example_account?: Prisma.example_accountUncheckedCreateNestedManyWithoutExample_userInput
  example_session?: Prisma.example_sessionUncheckedCreateNestedManyWithoutExample_userInput
}

export type example_userUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  example_account?: Prisma.example_accountUpdateManyWithoutExample_userNestedInput
  example_session?: Prisma.example_sessionUpdateManyWithoutExample_userNestedInput
}

export type example_userUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  example_account?: Prisma.example_accountUncheckedUpdateManyWithoutExample_userNestedInput
  example_session?: Prisma.example_sessionUncheckedUpdateManyWithoutExample_userNestedInput
}

export type example_userCreateManyInput = {
  id: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type example_userUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type example_userUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Example_userScalarRelationFilter = {
  is?: Prisma.example_userWhereInput
  isNot?: Prisma.example_userWhereInput
}

export type example_userCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type example_userMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type example_userMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  email_verified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type example_userCreateNestedOneWithoutExample_accountInput = {
  create?: Prisma.XOR<Prisma.example_userCreateWithoutExample_accountInput, Prisma.example_userUncheckedCreateWithoutExample_accountInput>
  connectOrCreate?: Prisma.example_userCreateOrConnectWithoutExample_accountInput
  connect?: Prisma.example_userWhereUniqueInput
}

export type example_userUpdateOneRequiredWithoutExample_accountNestedInput = {
  create?: Prisma.XOR<Prisma.example_userCreateWithoutExample_accountInput, Prisma.example_userUncheckedCreateWithoutExample_accountInput>
  connectOrCreate?: Prisma.example_userCreateOrConnectWithoutExample_accountInput
  upsert?: Prisma.example_userUpsertWithoutExample_accountInput
  connect?: Prisma.example_userWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.example_userUpdateToOneWithWhereWithoutExample_accountInput, Prisma.example_userUpdateWithoutExample_accountInput>, Prisma.example_userUncheckedUpdateWithoutExample_accountInput>
}

export type example_userCreateNestedOneWithoutExample_sessionInput = {
  create?: Prisma.XOR<Prisma.example_userCreateWithoutExample_sessionInput, Prisma.example_userUncheckedCreateWithoutExample_sessionInput>
  connectOrCreate?: Prisma.example_userCreateOrConnectWithoutExample_sessionInput
  connect?: Prisma.example_userWhereUniqueInput
}

export type example_userUpdateOneRequiredWithoutExample_sessionNestedInput = {
  create?: Prisma.XOR<Prisma.example_userCreateWithoutExample_sessionInput, Prisma.example_userUncheckedCreateWithoutExample_sessionInput>
  connectOrCreate?: Prisma.example_userCreateOrConnectWithoutExample_sessionInput
  upsert?: Prisma.example_userUpsertWithoutExample_sessionInput
  connect?: Prisma.example_userWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.example_userUpdateToOneWithWhereWithoutExample_sessionInput, Prisma.example_userUpdateWithoutExample_sessionInput>, Prisma.example_userUncheckedUpdateWithoutExample_sessionInput>
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type example_userCreateWithoutExample_accountInput = {
  id: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  example_session?: Prisma.example_sessionCreateNestedManyWithoutExample_userInput
}

export type example_userUncheckedCreateWithoutExample_accountInput = {
  id: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  example_session?: Prisma.example_sessionUncheckedCreateNestedManyWithoutExample_userInput
}

export type example_userCreateOrConnectWithoutExample_accountInput = {
  where: Prisma.example_userWhereUniqueInput
  create: Prisma.XOR<Prisma.example_userCreateWithoutExample_accountInput, Prisma.example_userUncheckedCreateWithoutExample_accountInput>
}

export type example_userUpsertWithoutExample_accountInput = {
  update: Prisma.XOR<Prisma.example_userUpdateWithoutExample_accountInput, Prisma.example_userUncheckedUpdateWithoutExample_accountInput>
  create: Prisma.XOR<Prisma.example_userCreateWithoutExample_accountInput, Prisma.example_userUncheckedCreateWithoutExample_accountInput>
  where?: Prisma.example_userWhereInput
}

export type example_userUpdateToOneWithWhereWithoutExample_accountInput = {
  where?: Prisma.example_userWhereInput
  data: Prisma.XOR<Prisma.example_userUpdateWithoutExample_accountInput, Prisma.example_userUncheckedUpdateWithoutExample_accountInput>
}

export type example_userUpdateWithoutExample_accountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  example_session?: Prisma.example_sessionUpdateManyWithoutExample_userNestedInput
}

export type example_userUncheckedUpdateWithoutExample_accountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  example_session?: Prisma.example_sessionUncheckedUpdateManyWithoutExample_userNestedInput
}

export type example_userCreateWithoutExample_sessionInput = {
  id: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  example_account?: Prisma.example_accountCreateNestedManyWithoutExample_userInput
}

export type example_userUncheckedCreateWithoutExample_sessionInput = {
  id: string
  name: string
  email: string
  email_verified?: boolean
  image?: string | null
  created_at?: Date | string
  updated_at?: Date | string
  example_account?: Prisma.example_accountUncheckedCreateNestedManyWithoutExample_userInput
}

export type example_userCreateOrConnectWithoutExample_sessionInput = {
  where: Prisma.example_userWhereUniqueInput
  create: Prisma.XOR<Prisma.example_userCreateWithoutExample_sessionInput, Prisma.example_userUncheckedCreateWithoutExample_sessionInput>
}

export type example_userUpsertWithoutExample_sessionInput = {
  update: Prisma.XOR<Prisma.example_userUpdateWithoutExample_sessionInput, Prisma.example_userUncheckedUpdateWithoutExample_sessionInput>
  create: Prisma.XOR<Prisma.example_userCreateWithoutExample_sessionInput, Prisma.example_userUncheckedCreateWithoutExample_sessionInput>
  where?: Prisma.example_userWhereInput
}

export type example_userUpdateToOneWithWhereWithoutExample_sessionInput = {
  where?: Prisma.example_userWhereInput
  data: Prisma.XOR<Prisma.example_userUpdateWithoutExample_sessionInput, Prisma.example_userUncheckedUpdateWithoutExample_sessionInput>
}

export type example_userUpdateWithoutExample_sessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  example_account?: Prisma.example_accountUpdateManyWithoutExample_userNestedInput
}

export type example_userUncheckedUpdateWithoutExample_sessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  email_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  example_account?: Prisma.example_accountUncheckedUpdateManyWithoutExample_userNestedInput
}


/**
 * Count Type Example_userCountOutputType
 */

export type Example_userCountOutputType = {
  example_account: number
  example_session: number
}

export type Example_userCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  example_account?: boolean | Example_userCountOutputTypeCountExample_accountArgs
  example_session?: boolean | Example_userCountOutputTypeCountExample_sessionArgs
}

/**
 * Example_userCountOutputType without action
 */
export type Example_userCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Example_userCountOutputType
   */
  select?: Prisma.Example_userCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Example_userCountOutputType without action
 */
export type Example_userCountOutputTypeCountExample_accountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.example_accountWhereInput
}

/**
 * Example_userCountOutputType without action
 */
export type Example_userCountOutputTypeCountExample_sessionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.example_sessionWhereInput
}


export type example_userSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
  example_account?: boolean | Prisma.example_user$example_accountArgs<ExtArgs>
  example_session?: boolean | Prisma.example_user$example_sessionArgs<ExtArgs>
  _count?: boolean | Prisma.Example_userCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["example_user"]>

export type example_userSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["example_user"]>

export type example_userSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["example_user"]>

export type example_userSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  email_verified?: boolean
  image?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type example_userOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "email_verified" | "image" | "created_at" | "updated_at", ExtArgs["result"]["example_user"]>
export type example_userInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  example_account?: boolean | Prisma.example_user$example_accountArgs<ExtArgs>
  example_session?: boolean | Prisma.example_user$example_sessionArgs<ExtArgs>
  _count?: boolean | Prisma.Example_userCountOutputTypeDefaultArgs<ExtArgs>
}
export type example_userIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type example_userIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $example_userPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "example_user"
  objects: {
    example_account: Prisma.$example_accountPayload<ExtArgs>[]
    example_session: Prisma.$example_sessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    email_verified: boolean
    image: string | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["example_user"]>
  composites: {}
}

export type example_userGetPayload<S extends boolean | null | undefined | example_userDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$example_userPayload, S>

export type example_userCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<example_userFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Example_userCountAggregateInputType | true
  }

export interface example_userDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['example_user'], meta: { name: 'example_user' } }
  /**
   * Find zero or one Example_user that matches the filter.
   * @param {example_userFindUniqueArgs} args - Arguments to find a Example_user
   * @example
   * // Get one Example_user
   * const example_user = await prisma.example_user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends example_userFindUniqueArgs>(args: Prisma.SelectSubset<T, example_userFindUniqueArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Example_user that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {example_userFindUniqueOrThrowArgs} args - Arguments to find a Example_user
   * @example
   * // Get one Example_user
   * const example_user = await prisma.example_user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends example_userFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, example_userFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Example_user that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {example_userFindFirstArgs} args - Arguments to find a Example_user
   * @example
   * // Get one Example_user
   * const example_user = await prisma.example_user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends example_userFindFirstArgs>(args?: Prisma.SelectSubset<T, example_userFindFirstArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Example_user that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {example_userFindFirstOrThrowArgs} args - Arguments to find a Example_user
   * @example
   * // Get one Example_user
   * const example_user = await prisma.example_user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends example_userFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, example_userFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Example_users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {example_userFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Example_users
   * const example_users = await prisma.example_user.findMany()
   * 
   * // Get first 10 Example_users
   * const example_users = await prisma.example_user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const example_userWithIdOnly = await prisma.example_user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends example_userFindManyArgs>(args?: Prisma.SelectSubset<T, example_userFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Example_user.
   * @param {example_userCreateArgs} args - Arguments to create a Example_user.
   * @example
   * // Create one Example_user
   * const Example_user = await prisma.example_user.create({
   *   data: {
   *     // ... data to create a Example_user
   *   }
   * })
   * 
   */
  create<T extends example_userCreateArgs>(args: Prisma.SelectSubset<T, example_userCreateArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Example_users.
   * @param {example_userCreateManyArgs} args - Arguments to create many Example_users.
   * @example
   * // Create many Example_users
   * const example_user = await prisma.example_user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends example_userCreateManyArgs>(args?: Prisma.SelectSubset<T, example_userCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Example_users and returns the data saved in the database.
   * @param {example_userCreateManyAndReturnArgs} args - Arguments to create many Example_users.
   * @example
   * // Create many Example_users
   * const example_user = await prisma.example_user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Example_users and only return the `id`
   * const example_userWithIdOnly = await prisma.example_user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends example_userCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, example_userCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Example_user.
   * @param {example_userDeleteArgs} args - Arguments to delete one Example_user.
   * @example
   * // Delete one Example_user
   * const Example_user = await prisma.example_user.delete({
   *   where: {
   *     // ... filter to delete one Example_user
   *   }
   * })
   * 
   */
  delete<T extends example_userDeleteArgs>(args: Prisma.SelectSubset<T, example_userDeleteArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Example_user.
   * @param {example_userUpdateArgs} args - Arguments to update one Example_user.
   * @example
   * // Update one Example_user
   * const example_user = await prisma.example_user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends example_userUpdateArgs>(args: Prisma.SelectSubset<T, example_userUpdateArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Example_users.
   * @param {example_userDeleteManyArgs} args - Arguments to filter Example_users to delete.
   * @example
   * // Delete a few Example_users
   * const { count } = await prisma.example_user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends example_userDeleteManyArgs>(args?: Prisma.SelectSubset<T, example_userDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Example_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {example_userUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Example_users
   * const example_user = await prisma.example_user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends example_userUpdateManyArgs>(args: Prisma.SelectSubset<T, example_userUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Example_users and returns the data updated in the database.
   * @param {example_userUpdateManyAndReturnArgs} args - Arguments to update many Example_users.
   * @example
   * // Update many Example_users
   * const example_user = await prisma.example_user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Example_users and only return the `id`
   * const example_userWithIdOnly = await prisma.example_user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends example_userUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, example_userUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Example_user.
   * @param {example_userUpsertArgs} args - Arguments to update or create a Example_user.
   * @example
   * // Update or create a Example_user
   * const example_user = await prisma.example_user.upsert({
   *   create: {
   *     // ... data to create a Example_user
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Example_user we want to update
   *   }
   * })
   */
  upsert<T extends example_userUpsertArgs>(args: Prisma.SelectSubset<T, example_userUpsertArgs<ExtArgs>>): Prisma.Prisma__example_userClient<runtime.Types.Result.GetResult<Prisma.$example_userPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Example_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {example_userCountArgs} args - Arguments to filter Example_users to count.
   * @example
   * // Count the number of Example_users
   * const count = await prisma.example_user.count({
   *   where: {
   *     // ... the filter for the Example_users we want to count
   *   }
   * })
  **/
  count<T extends example_userCountArgs>(
    args?: Prisma.Subset<T, example_userCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Example_userCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Example_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Example_userAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Example_userAggregateArgs>(args: Prisma.Subset<T, Example_userAggregateArgs>): Prisma.PrismaPromise<GetExample_userAggregateType<T>>

  /**
   * Group by Example_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {example_userGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends example_userGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: example_userGroupByArgs['orderBy'] }
      : { orderBy?: example_userGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, example_userGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExample_userGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the example_user model
 */
readonly fields: example_userFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for example_user.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__example_userClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  example_account<T extends Prisma.example_user$example_accountArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.example_user$example_accountArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$example_accountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  example_session<T extends Prisma.example_user$example_sessionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.example_user$example_sessionArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$example_sessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the example_user model
 */
export interface example_userFieldRefs {
  readonly id: Prisma.FieldRef<"example_user", 'String'>
  readonly name: Prisma.FieldRef<"example_user", 'String'>
  readonly email: Prisma.FieldRef<"example_user", 'String'>
  readonly email_verified: Prisma.FieldRef<"example_user", 'Boolean'>
  readonly image: Prisma.FieldRef<"example_user", 'String'>
  readonly created_at: Prisma.FieldRef<"example_user", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"example_user", 'DateTime'>
}
    

// Custom InputTypes
/**
 * example_user findUnique
 */
export type example_userFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * Filter, which example_user to fetch.
   */
  where: Prisma.example_userWhereUniqueInput
}

/**
 * example_user findUniqueOrThrow
 */
export type example_userFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * Filter, which example_user to fetch.
   */
  where: Prisma.example_userWhereUniqueInput
}

/**
 * example_user findFirst
 */
export type example_userFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * Filter, which example_user to fetch.
   */
  where?: Prisma.example_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of example_users to fetch.
   */
  orderBy?: Prisma.example_userOrderByWithRelationInput | Prisma.example_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for example_users.
   */
  cursor?: Prisma.example_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` example_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` example_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of example_users.
   */
  distinct?: Prisma.Example_userScalarFieldEnum | Prisma.Example_userScalarFieldEnum[]
}

/**
 * example_user findFirstOrThrow
 */
export type example_userFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * Filter, which example_user to fetch.
   */
  where?: Prisma.example_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of example_users to fetch.
   */
  orderBy?: Prisma.example_userOrderByWithRelationInput | Prisma.example_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for example_users.
   */
  cursor?: Prisma.example_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` example_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` example_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of example_users.
   */
  distinct?: Prisma.Example_userScalarFieldEnum | Prisma.Example_userScalarFieldEnum[]
}

/**
 * example_user findMany
 */
export type example_userFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * Filter, which example_users to fetch.
   */
  where?: Prisma.example_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of example_users to fetch.
   */
  orderBy?: Prisma.example_userOrderByWithRelationInput | Prisma.example_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing example_users.
   */
  cursor?: Prisma.example_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` example_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` example_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of example_users.
   */
  distinct?: Prisma.Example_userScalarFieldEnum | Prisma.Example_userScalarFieldEnum[]
}

/**
 * example_user create
 */
export type example_userCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * The data needed to create a example_user.
   */
  data: Prisma.XOR<Prisma.example_userCreateInput, Prisma.example_userUncheckedCreateInput>
}

/**
 * example_user createMany
 */
export type example_userCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many example_users.
   */
  data: Prisma.example_userCreateManyInput | Prisma.example_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * example_user createManyAndReturn
 */
export type example_userCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * The data used to create many example_users.
   */
  data: Prisma.example_userCreateManyInput | Prisma.example_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * example_user update
 */
export type example_userUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * The data needed to update a example_user.
   */
  data: Prisma.XOR<Prisma.example_userUpdateInput, Prisma.example_userUncheckedUpdateInput>
  /**
   * Choose, which example_user to update.
   */
  where: Prisma.example_userWhereUniqueInput
}

/**
 * example_user updateMany
 */
export type example_userUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update example_users.
   */
  data: Prisma.XOR<Prisma.example_userUpdateManyMutationInput, Prisma.example_userUncheckedUpdateManyInput>
  /**
   * Filter which example_users to update
   */
  where?: Prisma.example_userWhereInput
  /**
   * Limit how many example_users to update.
   */
  limit?: number
}

/**
 * example_user updateManyAndReturn
 */
export type example_userUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * The data used to update example_users.
   */
  data: Prisma.XOR<Prisma.example_userUpdateManyMutationInput, Prisma.example_userUncheckedUpdateManyInput>
  /**
   * Filter which example_users to update
   */
  where?: Prisma.example_userWhereInput
  /**
   * Limit how many example_users to update.
   */
  limit?: number
}

/**
 * example_user upsert
 */
export type example_userUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * The filter to search for the example_user to update in case it exists.
   */
  where: Prisma.example_userWhereUniqueInput
  /**
   * In case the example_user found by the `where` argument doesn't exist, create a new example_user with this data.
   */
  create: Prisma.XOR<Prisma.example_userCreateInput, Prisma.example_userUncheckedCreateInput>
  /**
   * In case the example_user was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.example_userUpdateInput, Prisma.example_userUncheckedUpdateInput>
}

/**
 * example_user delete
 */
export type example_userDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
  /**
   * Filter which example_user to delete.
   */
  where: Prisma.example_userWhereUniqueInput
}

/**
 * example_user deleteMany
 */
export type example_userDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which example_users to delete
   */
  where?: Prisma.example_userWhereInput
  /**
   * Limit how many example_users to delete.
   */
  limit?: number
}

/**
 * example_user.example_account
 */
export type example_user$example_accountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_account
   */
  select?: Prisma.example_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_account
   */
  omit?: Prisma.example_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_accountInclude<ExtArgs> | null
  where?: Prisma.example_accountWhereInput
  orderBy?: Prisma.example_accountOrderByWithRelationInput | Prisma.example_accountOrderByWithRelationInput[]
  cursor?: Prisma.example_accountWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Example_accountScalarFieldEnum | Prisma.Example_accountScalarFieldEnum[]
}

/**
 * example_user.example_session
 */
export type example_user$example_sessionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_session
   */
  select?: Prisma.example_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_session
   */
  omit?: Prisma.example_sessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_sessionInclude<ExtArgs> | null
  where?: Prisma.example_sessionWhereInput
  orderBy?: Prisma.example_sessionOrderByWithRelationInput | Prisma.example_sessionOrderByWithRelationInput[]
  cursor?: Prisma.example_sessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Example_sessionScalarFieldEnum | Prisma.Example_sessionScalarFieldEnum[]
}

/**
 * example_user without action
 */
export type example_userDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the example_user
   */
  select?: Prisma.example_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the example_user
   */
  omit?: Prisma.example_userOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.example_userInclude<ExtArgs> | null
}
