
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `interviews_tool_account` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model interviews_tool_account
 * 
 */
export type interviews_tool_accountModel = runtime.Types.Result.DefaultSelection<Prisma.$interviews_tool_accountPayload>

export type AggregateInterviews_tool_account = {
  _count: Interviews_tool_accountCountAggregateOutputType | null
  _min: Interviews_tool_accountMinAggregateOutputType | null
  _max: Interviews_tool_accountMaxAggregateOutputType | null
}

export type Interviews_tool_accountMinAggregateOutputType = {
  id: string | null
  account_id: string | null
  provider_id: string | null
  user_id: string | null
  access_token: string | null
  refresh_token: string | null
  id_token: string | null
  access_token_expires_at: Date | null
  refresh_token_expires_at: Date | null
  scope: string | null
  password: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Interviews_tool_accountMaxAggregateOutputType = {
  id: string | null
  account_id: string | null
  provider_id: string | null
  user_id: string | null
  access_token: string | null
  refresh_token: string | null
  id_token: string | null
  access_token_expires_at: Date | null
  refresh_token_expires_at: Date | null
  scope: string | null
  password: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Interviews_tool_accountCountAggregateOutputType = {
  id: number
  account_id: number
  provider_id: number
  user_id: number
  access_token: number
  refresh_token: number
  id_token: number
  access_token_expires_at: number
  refresh_token_expires_at: number
  scope: number
  password: number
  created_at: number
  updated_at: number
  _all: number
}


export type Interviews_tool_accountMinAggregateInputType = {
  id?: true
  account_id?: true
  provider_id?: true
  user_id?: true
  access_token?: true
  refresh_token?: true
  id_token?: true
  access_token_expires_at?: true
  refresh_token_expires_at?: true
  scope?: true
  password?: true
  created_at?: true
  updated_at?: true
}

export type Interviews_tool_accountMaxAggregateInputType = {
  id?: true
  account_id?: true
  provider_id?: true
  user_id?: true
  access_token?: true
  refresh_token?: true
  id_token?: true
  access_token_expires_at?: true
  refresh_token_expires_at?: true
  scope?: true
  password?: true
  created_at?: true
  updated_at?: true
}

export type Interviews_tool_accountCountAggregateInputType = {
  id?: true
  account_id?: true
  provider_id?: true
  user_id?: true
  access_token?: true
  refresh_token?: true
  id_token?: true
  access_token_expires_at?: true
  refresh_token_expires_at?: true
  scope?: true
  password?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Interviews_tool_accountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which interviews_tool_account to aggregate.
   */
  where?: Prisma.interviews_tool_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of interviews_tool_accounts to fetch.
   */
  orderBy?: Prisma.interviews_tool_accountOrderByWithRelationInput | Prisma.interviews_tool_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.interviews_tool_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` interviews_tool_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` interviews_tool_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned interviews_tool_accounts
  **/
  _count?: true | Interviews_tool_accountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Interviews_tool_accountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Interviews_tool_accountMaxAggregateInputType
}

export type GetInterviews_tool_accountAggregateType<T extends Interviews_tool_accountAggregateArgs> = {
      [P in keyof T & keyof AggregateInterviews_tool_account]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInterviews_tool_account[P]>
    : Prisma.GetScalarType<T[P], AggregateInterviews_tool_account[P]>
}




export type interviews_tool_accountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.interviews_tool_accountWhereInput
  orderBy?: Prisma.interviews_tool_accountOrderByWithAggregationInput | Prisma.interviews_tool_accountOrderByWithAggregationInput[]
  by: Prisma.Interviews_tool_accountScalarFieldEnum[] | Prisma.Interviews_tool_accountScalarFieldEnum
  having?: Prisma.interviews_tool_accountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Interviews_tool_accountCountAggregateInputType | true
  _min?: Interviews_tool_accountMinAggregateInputType
  _max?: Interviews_tool_accountMaxAggregateInputType
}

export type Interviews_tool_accountGroupByOutputType = {
  id: string
  account_id: string
  provider_id: string
  user_id: string
  access_token: string | null
  refresh_token: string | null
  id_token: string | null
  access_token_expires_at: Date | null
  refresh_token_expires_at: Date | null
  scope: string | null
  password: string | null
  created_at: Date
  updated_at: Date
  _count: Interviews_tool_accountCountAggregateOutputType | null
  _min: Interviews_tool_accountMinAggregateOutputType | null
  _max: Interviews_tool_accountMaxAggregateOutputType | null
}

export type GetInterviews_tool_accountGroupByPayload<T extends interviews_tool_accountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Interviews_tool_accountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Interviews_tool_accountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Interviews_tool_accountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Interviews_tool_accountGroupByOutputType[P]>
      }
    >
  >



export type interviews_tool_accountWhereInput = {
  AND?: Prisma.interviews_tool_accountWhereInput | Prisma.interviews_tool_accountWhereInput[]
  OR?: Prisma.interviews_tool_accountWhereInput[]
  NOT?: Prisma.interviews_tool_accountWhereInput | Prisma.interviews_tool_accountWhereInput[]
  id?: Prisma.StringFilter<"interviews_tool_account"> | string
  account_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  provider_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  user_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  access_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  refresh_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  id_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  access_token_expires_at?: Prisma.DateTimeNullableFilter<"interviews_tool_account"> | Date | string | null
  refresh_token_expires_at?: Prisma.DateTimeNullableFilter<"interviews_tool_account"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  password?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  created_at?: Prisma.DateTimeFilter<"interviews_tool_account"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"interviews_tool_account"> | Date | string
  interviews_tool_user?: Prisma.XOR<Prisma.Interviews_tool_userScalarRelationFilter, Prisma.interviews_tool_userWhereInput>
}

export type interviews_tool_accountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token?: Prisma.SortOrderInput | Prisma.SortOrder
  id_token?: Prisma.SortOrderInput | Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  interviews_tool_user?: Prisma.interviews_tool_userOrderByWithRelationInput
}

export type interviews_tool_accountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.interviews_tool_accountWhereInput | Prisma.interviews_tool_accountWhereInput[]
  OR?: Prisma.interviews_tool_accountWhereInput[]
  NOT?: Prisma.interviews_tool_accountWhereInput | Prisma.interviews_tool_accountWhereInput[]
  account_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  provider_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  user_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  access_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  refresh_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  id_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  access_token_expires_at?: Prisma.DateTimeNullableFilter<"interviews_tool_account"> | Date | string | null
  refresh_token_expires_at?: Prisma.DateTimeNullableFilter<"interviews_tool_account"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  password?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  created_at?: Prisma.DateTimeFilter<"interviews_tool_account"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"interviews_tool_account"> | Date | string
  interviews_tool_user?: Prisma.XOR<Prisma.Interviews_tool_userScalarRelationFilter, Prisma.interviews_tool_userWhereInput>
}, "id">

export type interviews_tool_accountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token?: Prisma.SortOrderInput | Prisma.SortOrder
  id_token?: Prisma.SortOrderInput | Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.interviews_tool_accountCountOrderByAggregateInput
  _max?: Prisma.interviews_tool_accountMaxOrderByAggregateInput
  _min?: Prisma.interviews_tool_accountMinOrderByAggregateInput
}

export type interviews_tool_accountScalarWhereWithAggregatesInput = {
  AND?: Prisma.interviews_tool_accountScalarWhereWithAggregatesInput | Prisma.interviews_tool_accountScalarWhereWithAggregatesInput[]
  OR?: Prisma.interviews_tool_accountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.interviews_tool_accountScalarWhereWithAggregatesInput | Prisma.interviews_tool_accountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"interviews_tool_account"> | string
  account_id?: Prisma.StringWithAggregatesFilter<"interviews_tool_account"> | string
  provider_id?: Prisma.StringWithAggregatesFilter<"interviews_tool_account"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"interviews_tool_account"> | string
  access_token?: Prisma.StringNullableWithAggregatesFilter<"interviews_tool_account"> | string | null
  refresh_token?: Prisma.StringNullableWithAggregatesFilter<"interviews_tool_account"> | string | null
  id_token?: Prisma.StringNullableWithAggregatesFilter<"interviews_tool_account"> | string | null
  access_token_expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"interviews_tool_account"> | Date | string | null
  refresh_token_expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"interviews_tool_account"> | Date | string | null
  scope?: Prisma.StringNullableWithAggregatesFilter<"interviews_tool_account"> | string | null
  password?: Prisma.StringNullableWithAggregatesFilter<"interviews_tool_account"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"interviews_tool_account"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"interviews_tool_account"> | Date | string
}

export type interviews_tool_accountCreateInput = {
  id: string
  account_id: string
  provider_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
  interviews_tool_user: Prisma.interviews_tool_userCreateNestedOneWithoutInterviews_tool_accountInput
}

export type interviews_tool_accountUncheckedCreateInput = {
  id: string
  account_id: string
  provider_id: string
  user_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type interviews_tool_accountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  interviews_tool_user?: Prisma.interviews_tool_userUpdateOneRequiredWithoutInterviews_tool_accountNestedInput
}

export type interviews_tool_accountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type interviews_tool_accountCreateManyInput = {
  id: string
  account_id: string
  provider_id: string
  user_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type interviews_tool_accountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type interviews_tool_accountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type interviews_tool_accountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrder
  refresh_token?: Prisma.SortOrder
  id_token?: Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  password?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type interviews_tool_accountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrder
  refresh_token?: Prisma.SortOrder
  id_token?: Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  password?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type interviews_tool_accountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrder
  refresh_token?: Prisma.SortOrder
  id_token?: Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  password?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Interviews_tool_accountListRelationFilter = {
  every?: Prisma.interviews_tool_accountWhereInput
  some?: Prisma.interviews_tool_accountWhereInput
  none?: Prisma.interviews_tool_accountWhereInput
}

export type interviews_tool_accountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type interviews_tool_accountCreateNestedManyWithoutInterviews_tool_userInput = {
  create?: Prisma.XOR<Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput> | Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput[] | Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput[]
  connectOrCreate?: Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput[]
  createMany?: Prisma.interviews_tool_accountCreateManyInterviews_tool_userInputEnvelope
  connect?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
}

export type interviews_tool_accountUncheckedCreateNestedManyWithoutInterviews_tool_userInput = {
  create?: Prisma.XOR<Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput> | Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput[] | Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput[]
  connectOrCreate?: Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput[]
  createMany?: Prisma.interviews_tool_accountCreateManyInterviews_tool_userInputEnvelope
  connect?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
}

export type interviews_tool_accountUpdateManyWithoutInterviews_tool_userNestedInput = {
  create?: Prisma.XOR<Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput> | Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput[] | Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput[]
  connectOrCreate?: Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput[]
  upsert?: Prisma.interviews_tool_accountUpsertWithWhereUniqueWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountUpsertWithWhereUniqueWithoutInterviews_tool_userInput[]
  createMany?: Prisma.interviews_tool_accountCreateManyInterviews_tool_userInputEnvelope
  set?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  disconnect?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  delete?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  connect?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  update?: Prisma.interviews_tool_accountUpdateWithWhereUniqueWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountUpdateWithWhereUniqueWithoutInterviews_tool_userInput[]
  updateMany?: Prisma.interviews_tool_accountUpdateManyWithWhereWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountUpdateManyWithWhereWithoutInterviews_tool_userInput[]
  deleteMany?: Prisma.interviews_tool_accountScalarWhereInput | Prisma.interviews_tool_accountScalarWhereInput[]
}

export type interviews_tool_accountUncheckedUpdateManyWithoutInterviews_tool_userNestedInput = {
  create?: Prisma.XOR<Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput> | Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput[] | Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput[]
  connectOrCreate?: Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput[]
  upsert?: Prisma.interviews_tool_accountUpsertWithWhereUniqueWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountUpsertWithWhereUniqueWithoutInterviews_tool_userInput[]
  createMany?: Prisma.interviews_tool_accountCreateManyInterviews_tool_userInputEnvelope
  set?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  disconnect?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  delete?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  connect?: Prisma.interviews_tool_accountWhereUniqueInput | Prisma.interviews_tool_accountWhereUniqueInput[]
  update?: Prisma.interviews_tool_accountUpdateWithWhereUniqueWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountUpdateWithWhereUniqueWithoutInterviews_tool_userInput[]
  updateMany?: Prisma.interviews_tool_accountUpdateManyWithWhereWithoutInterviews_tool_userInput | Prisma.interviews_tool_accountUpdateManyWithWhereWithoutInterviews_tool_userInput[]
  deleteMany?: Prisma.interviews_tool_accountScalarWhereInput | Prisma.interviews_tool_accountScalarWhereInput[]
}

export type interviews_tool_accountCreateWithoutInterviews_tool_userInput = {
  id: string
  account_id: string
  provider_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput = {
  id: string
  account_id: string
  provider_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type interviews_tool_accountCreateOrConnectWithoutInterviews_tool_userInput = {
  where: Prisma.interviews_tool_accountWhereUniqueInput
  create: Prisma.XOR<Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput>
}

export type interviews_tool_accountCreateManyInterviews_tool_userInputEnvelope = {
  data: Prisma.interviews_tool_accountCreateManyInterviews_tool_userInput | Prisma.interviews_tool_accountCreateManyInterviews_tool_userInput[]
  skipDuplicates?: boolean
}

export type interviews_tool_accountUpsertWithWhereUniqueWithoutInterviews_tool_userInput = {
  where: Prisma.interviews_tool_accountWhereUniqueInput
  update: Prisma.XOR<Prisma.interviews_tool_accountUpdateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedUpdateWithoutInterviews_tool_userInput>
  create: Prisma.XOR<Prisma.interviews_tool_accountCreateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedCreateWithoutInterviews_tool_userInput>
}

export type interviews_tool_accountUpdateWithWhereUniqueWithoutInterviews_tool_userInput = {
  where: Prisma.interviews_tool_accountWhereUniqueInput
  data: Prisma.XOR<Prisma.interviews_tool_accountUpdateWithoutInterviews_tool_userInput, Prisma.interviews_tool_accountUncheckedUpdateWithoutInterviews_tool_userInput>
}

export type interviews_tool_accountUpdateManyWithWhereWithoutInterviews_tool_userInput = {
  where: Prisma.interviews_tool_accountScalarWhereInput
  data: Prisma.XOR<Prisma.interviews_tool_accountUpdateManyMutationInput, Prisma.interviews_tool_accountUncheckedUpdateManyWithoutInterviews_tool_userInput>
}

export type interviews_tool_accountScalarWhereInput = {
  AND?: Prisma.interviews_tool_accountScalarWhereInput | Prisma.interviews_tool_accountScalarWhereInput[]
  OR?: Prisma.interviews_tool_accountScalarWhereInput[]
  NOT?: Prisma.interviews_tool_accountScalarWhereInput | Prisma.interviews_tool_accountScalarWhereInput[]
  id?: Prisma.StringFilter<"interviews_tool_account"> | string
  account_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  provider_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  user_id?: Prisma.StringFilter<"interviews_tool_account"> | string
  access_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  refresh_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  id_token?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  access_token_expires_at?: Prisma.DateTimeNullableFilter<"interviews_tool_account"> | Date | string | null
  refresh_token_expires_at?: Prisma.DateTimeNullableFilter<"interviews_tool_account"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  password?: Prisma.StringNullableFilter<"interviews_tool_account"> | string | null
  created_at?: Prisma.DateTimeFilter<"interviews_tool_account"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"interviews_tool_account"> | Date | string
}

export type interviews_tool_accountCreateManyInterviews_tool_userInput = {
  id: string
  account_id: string
  provider_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type interviews_tool_accountUpdateWithoutInterviews_tool_userInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type interviews_tool_accountUncheckedUpdateWithoutInterviews_tool_userInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type interviews_tool_accountUncheckedUpdateManyWithoutInterviews_tool_userInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type interviews_tool_accountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
  interviews_tool_user?: boolean | Prisma.interviews_tool_userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interviews_tool_account"]>

export type interviews_tool_accountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
  interviews_tool_user?: boolean | Prisma.interviews_tool_userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interviews_tool_account"]>

export type interviews_tool_accountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
  interviews_tool_user?: boolean | Prisma.interviews_tool_userDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interviews_tool_account"]>

export type interviews_tool_accountSelectScalar = {
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type interviews_tool_accountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "account_id" | "provider_id" | "user_id" | "access_token" | "refresh_token" | "id_token" | "access_token_expires_at" | "refresh_token_expires_at" | "scope" | "password" | "created_at" | "updated_at", ExtArgs["result"]["interviews_tool_account"]>
export type interviews_tool_accountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interviews_tool_user?: boolean | Prisma.interviews_tool_userDefaultArgs<ExtArgs>
}
export type interviews_tool_accountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interviews_tool_user?: boolean | Prisma.interviews_tool_userDefaultArgs<ExtArgs>
}
export type interviews_tool_accountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interviews_tool_user?: boolean | Prisma.interviews_tool_userDefaultArgs<ExtArgs>
}

export type $interviews_tool_accountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "interviews_tool_account"
  objects: {
    interviews_tool_user: Prisma.$interviews_tool_userPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    account_id: string
    provider_id: string
    user_id: string
    access_token: string | null
    refresh_token: string | null
    id_token: string | null
    access_token_expires_at: Date | null
    refresh_token_expires_at: Date | null
    scope: string | null
    password: string | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["interviews_tool_account"]>
  composites: {}
}

export type interviews_tool_accountGetPayload<S extends boolean | null | undefined | interviews_tool_accountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload, S>

export type interviews_tool_accountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<interviews_tool_accountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Interviews_tool_accountCountAggregateInputType | true
  }

export interface interviews_tool_accountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['interviews_tool_account'], meta: { name: 'interviews_tool_account' } }
  /**
   * Find zero or one Interviews_tool_account that matches the filter.
   * @param {interviews_tool_accountFindUniqueArgs} args - Arguments to find a Interviews_tool_account
   * @example
   * // Get one Interviews_tool_account
   * const interviews_tool_account = await prisma.interviews_tool_account.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends interviews_tool_accountFindUniqueArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Interviews_tool_account that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {interviews_tool_accountFindUniqueOrThrowArgs} args - Arguments to find a Interviews_tool_account
   * @example
   * // Get one Interviews_tool_account
   * const interviews_tool_account = await prisma.interviews_tool_account.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends interviews_tool_accountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Interviews_tool_account that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {interviews_tool_accountFindFirstArgs} args - Arguments to find a Interviews_tool_account
   * @example
   * // Get one Interviews_tool_account
   * const interviews_tool_account = await prisma.interviews_tool_account.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends interviews_tool_accountFindFirstArgs>(args?: Prisma.SelectSubset<T, interviews_tool_accountFindFirstArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Interviews_tool_account that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {interviews_tool_accountFindFirstOrThrowArgs} args - Arguments to find a Interviews_tool_account
   * @example
   * // Get one Interviews_tool_account
   * const interviews_tool_account = await prisma.interviews_tool_account.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends interviews_tool_accountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, interviews_tool_accountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Interviews_tool_accounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {interviews_tool_accountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Interviews_tool_accounts
   * const interviews_tool_accounts = await prisma.interviews_tool_account.findMany()
   * 
   * // Get first 10 Interviews_tool_accounts
   * const interviews_tool_accounts = await prisma.interviews_tool_account.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const interviews_tool_accountWithIdOnly = await prisma.interviews_tool_account.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends interviews_tool_accountFindManyArgs>(args?: Prisma.SelectSubset<T, interviews_tool_accountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Interviews_tool_account.
   * @param {interviews_tool_accountCreateArgs} args - Arguments to create a Interviews_tool_account.
   * @example
   * // Create one Interviews_tool_account
   * const Interviews_tool_account = await prisma.interviews_tool_account.create({
   *   data: {
   *     // ... data to create a Interviews_tool_account
   *   }
   * })
   * 
   */
  create<T extends interviews_tool_accountCreateArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountCreateArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Interviews_tool_accounts.
   * @param {interviews_tool_accountCreateManyArgs} args - Arguments to create many Interviews_tool_accounts.
   * @example
   * // Create many Interviews_tool_accounts
   * const interviews_tool_account = await prisma.interviews_tool_account.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends interviews_tool_accountCreateManyArgs>(args?: Prisma.SelectSubset<T, interviews_tool_accountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Interviews_tool_accounts and returns the data saved in the database.
   * @param {interviews_tool_accountCreateManyAndReturnArgs} args - Arguments to create many Interviews_tool_accounts.
   * @example
   * // Create many Interviews_tool_accounts
   * const interviews_tool_account = await prisma.interviews_tool_account.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Interviews_tool_accounts and only return the `id`
   * const interviews_tool_accountWithIdOnly = await prisma.interviews_tool_account.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends interviews_tool_accountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, interviews_tool_accountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Interviews_tool_account.
   * @param {interviews_tool_accountDeleteArgs} args - Arguments to delete one Interviews_tool_account.
   * @example
   * // Delete one Interviews_tool_account
   * const Interviews_tool_account = await prisma.interviews_tool_account.delete({
   *   where: {
   *     // ... filter to delete one Interviews_tool_account
   *   }
   * })
   * 
   */
  delete<T extends interviews_tool_accountDeleteArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountDeleteArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Interviews_tool_account.
   * @param {interviews_tool_accountUpdateArgs} args - Arguments to update one Interviews_tool_account.
   * @example
   * // Update one Interviews_tool_account
   * const interviews_tool_account = await prisma.interviews_tool_account.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends interviews_tool_accountUpdateArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountUpdateArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Interviews_tool_accounts.
   * @param {interviews_tool_accountDeleteManyArgs} args - Arguments to filter Interviews_tool_accounts to delete.
   * @example
   * // Delete a few Interviews_tool_accounts
   * const { count } = await prisma.interviews_tool_account.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends interviews_tool_accountDeleteManyArgs>(args?: Prisma.SelectSubset<T, interviews_tool_accountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Interviews_tool_accounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {interviews_tool_accountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Interviews_tool_accounts
   * const interviews_tool_account = await prisma.interviews_tool_account.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends interviews_tool_accountUpdateManyArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Interviews_tool_accounts and returns the data updated in the database.
   * @param {interviews_tool_accountUpdateManyAndReturnArgs} args - Arguments to update many Interviews_tool_accounts.
   * @example
   * // Update many Interviews_tool_accounts
   * const interviews_tool_account = await prisma.interviews_tool_account.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Interviews_tool_accounts and only return the `id`
   * const interviews_tool_accountWithIdOnly = await prisma.interviews_tool_account.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends interviews_tool_accountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Interviews_tool_account.
   * @param {interviews_tool_accountUpsertArgs} args - Arguments to update or create a Interviews_tool_account.
   * @example
   * // Update or create a Interviews_tool_account
   * const interviews_tool_account = await prisma.interviews_tool_account.upsert({
   *   create: {
   *     // ... data to create a Interviews_tool_account
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Interviews_tool_account we want to update
   *   }
   * })
   */
  upsert<T extends interviews_tool_accountUpsertArgs>(args: Prisma.SelectSubset<T, interviews_tool_accountUpsertArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_accountClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_accountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Interviews_tool_accounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {interviews_tool_accountCountArgs} args - Arguments to filter Interviews_tool_accounts to count.
   * @example
   * // Count the number of Interviews_tool_accounts
   * const count = await prisma.interviews_tool_account.count({
   *   where: {
   *     // ... the filter for the Interviews_tool_accounts we want to count
   *   }
   * })
  **/
  count<T extends interviews_tool_accountCountArgs>(
    args?: Prisma.Subset<T, interviews_tool_accountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Interviews_tool_accountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Interviews_tool_account.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Interviews_tool_accountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Interviews_tool_accountAggregateArgs>(args: Prisma.Subset<T, Interviews_tool_accountAggregateArgs>): Prisma.PrismaPromise<GetInterviews_tool_accountAggregateType<T>>

  /**
   * Group by Interviews_tool_account.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {interviews_tool_accountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends interviews_tool_accountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: interviews_tool_accountGroupByArgs['orderBy'] }
      : { orderBy?: interviews_tool_accountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, interviews_tool_accountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInterviews_tool_accountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the interviews_tool_account model
 */
readonly fields: interviews_tool_accountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for interviews_tool_account.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__interviews_tool_accountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  interviews_tool_user<T extends Prisma.interviews_tool_userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.interviews_tool_userDefaultArgs<ExtArgs>>): Prisma.Prisma__interviews_tool_userClient<runtime.Types.Result.GetResult<Prisma.$interviews_tool_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the interviews_tool_account model
 */
export interface interviews_tool_accountFieldRefs {
  readonly id: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly account_id: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly provider_id: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly user_id: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly access_token: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly refresh_token: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly id_token: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly access_token_expires_at: Prisma.FieldRef<"interviews_tool_account", 'DateTime'>
  readonly refresh_token_expires_at: Prisma.FieldRef<"interviews_tool_account", 'DateTime'>
  readonly scope: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly password: Prisma.FieldRef<"interviews_tool_account", 'String'>
  readonly created_at: Prisma.FieldRef<"interviews_tool_account", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"interviews_tool_account", 'DateTime'>
}
    

// Custom InputTypes
/**
 * interviews_tool_account findUnique
 */
export type interviews_tool_accountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * Filter, which interviews_tool_account to fetch.
   */
  where: Prisma.interviews_tool_accountWhereUniqueInput
}

/**
 * interviews_tool_account findUniqueOrThrow
 */
export type interviews_tool_accountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * Filter, which interviews_tool_account to fetch.
   */
  where: Prisma.interviews_tool_accountWhereUniqueInput
}

/**
 * interviews_tool_account findFirst
 */
export type interviews_tool_accountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * Filter, which interviews_tool_account to fetch.
   */
  where?: Prisma.interviews_tool_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of interviews_tool_accounts to fetch.
   */
  orderBy?: Prisma.interviews_tool_accountOrderByWithRelationInput | Prisma.interviews_tool_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for interviews_tool_accounts.
   */
  cursor?: Prisma.interviews_tool_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` interviews_tool_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` interviews_tool_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of interviews_tool_accounts.
   */
  distinct?: Prisma.Interviews_tool_accountScalarFieldEnum | Prisma.Interviews_tool_accountScalarFieldEnum[]
}

/**
 * interviews_tool_account findFirstOrThrow
 */
export type interviews_tool_accountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * Filter, which interviews_tool_account to fetch.
   */
  where?: Prisma.interviews_tool_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of interviews_tool_accounts to fetch.
   */
  orderBy?: Prisma.interviews_tool_accountOrderByWithRelationInput | Prisma.interviews_tool_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for interviews_tool_accounts.
   */
  cursor?: Prisma.interviews_tool_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` interviews_tool_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` interviews_tool_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of interviews_tool_accounts.
   */
  distinct?: Prisma.Interviews_tool_accountScalarFieldEnum | Prisma.Interviews_tool_accountScalarFieldEnum[]
}

/**
 * interviews_tool_account findMany
 */
export type interviews_tool_accountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * Filter, which interviews_tool_accounts to fetch.
   */
  where?: Prisma.interviews_tool_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of interviews_tool_accounts to fetch.
   */
  orderBy?: Prisma.interviews_tool_accountOrderByWithRelationInput | Prisma.interviews_tool_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing interviews_tool_accounts.
   */
  cursor?: Prisma.interviews_tool_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` interviews_tool_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` interviews_tool_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of interviews_tool_accounts.
   */
  distinct?: Prisma.Interviews_tool_accountScalarFieldEnum | Prisma.Interviews_tool_accountScalarFieldEnum[]
}

/**
 * interviews_tool_account create
 */
export type interviews_tool_accountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * The data needed to create a interviews_tool_account.
   */
  data: Prisma.XOR<Prisma.interviews_tool_accountCreateInput, Prisma.interviews_tool_accountUncheckedCreateInput>
}

/**
 * interviews_tool_account createMany
 */
export type interviews_tool_accountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many interviews_tool_accounts.
   */
  data: Prisma.interviews_tool_accountCreateManyInput | Prisma.interviews_tool_accountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * interviews_tool_account createManyAndReturn
 */
export type interviews_tool_accountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * The data used to create many interviews_tool_accounts.
   */
  data: Prisma.interviews_tool_accountCreateManyInput | Prisma.interviews_tool_accountCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * interviews_tool_account update
 */
export type interviews_tool_accountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * The data needed to update a interviews_tool_account.
   */
  data: Prisma.XOR<Prisma.interviews_tool_accountUpdateInput, Prisma.interviews_tool_accountUncheckedUpdateInput>
  /**
   * Choose, which interviews_tool_account to update.
   */
  where: Prisma.interviews_tool_accountWhereUniqueInput
}

/**
 * interviews_tool_account updateMany
 */
export type interviews_tool_accountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update interviews_tool_accounts.
   */
  data: Prisma.XOR<Prisma.interviews_tool_accountUpdateManyMutationInput, Prisma.interviews_tool_accountUncheckedUpdateManyInput>
  /**
   * Filter which interviews_tool_accounts to update
   */
  where?: Prisma.interviews_tool_accountWhereInput
  /**
   * Limit how many interviews_tool_accounts to update.
   */
  limit?: number
}

/**
 * interviews_tool_account updateManyAndReturn
 */
export type interviews_tool_accountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * The data used to update interviews_tool_accounts.
   */
  data: Prisma.XOR<Prisma.interviews_tool_accountUpdateManyMutationInput, Prisma.interviews_tool_accountUncheckedUpdateManyInput>
  /**
   * Filter which interviews_tool_accounts to update
   */
  where?: Prisma.interviews_tool_accountWhereInput
  /**
   * Limit how many interviews_tool_accounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * interviews_tool_account upsert
 */
export type interviews_tool_accountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * The filter to search for the interviews_tool_account to update in case it exists.
   */
  where: Prisma.interviews_tool_accountWhereUniqueInput
  /**
   * In case the interviews_tool_account found by the `where` argument doesn't exist, create a new interviews_tool_account with this data.
   */
  create: Prisma.XOR<Prisma.interviews_tool_accountCreateInput, Prisma.interviews_tool_accountUncheckedCreateInput>
  /**
   * In case the interviews_tool_account was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.interviews_tool_accountUpdateInput, Prisma.interviews_tool_accountUncheckedUpdateInput>
}

/**
 * interviews_tool_account delete
 */
export type interviews_tool_accountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
  /**
   * Filter which interviews_tool_account to delete.
   */
  where: Prisma.interviews_tool_accountWhereUniqueInput
}

/**
 * interviews_tool_account deleteMany
 */
export type interviews_tool_accountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which interviews_tool_accounts to delete
   */
  where?: Prisma.interviews_tool_accountWhereInput
  /**
   * Limit how many interviews_tool_accounts to delete.
   */
  limit?: number
}

/**
 * interviews_tool_account without action
 */
export type interviews_tool_accountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the interviews_tool_account
   */
  select?: Prisma.interviews_tool_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the interviews_tool_account
   */
  omit?: Prisma.interviews_tool_accountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.interviews_tool_accountInclude<ExtArgs> | null
}
