
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `real_estate_broker_system_account` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model real_estate_broker_system_account
 * 
 */
export type real_estate_broker_system_accountModel = runtime.Types.Result.DefaultSelection<Prisma.$real_estate_broker_system_accountPayload>

export type AggregateReal_estate_broker_system_account = {
  _count: Real_estate_broker_system_accountCountAggregateOutputType | null
  _min: Real_estate_broker_system_accountMinAggregateOutputType | null
  _max: Real_estate_broker_system_accountMaxAggregateOutputType | null
}

export type Real_estate_broker_system_accountMinAggregateOutputType = {
  id: string | null
  account_id: string | null
  provider_id: string | null
  user_id: string | null
  access_token: string | null
  refresh_token: string | null
  id_token: string | null
  access_token_expires_at: Date | null
  refresh_token_expires_at: Date | null
  scope: string | null
  password: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Real_estate_broker_system_accountMaxAggregateOutputType = {
  id: string | null
  account_id: string | null
  provider_id: string | null
  user_id: string | null
  access_token: string | null
  refresh_token: string | null
  id_token: string | null
  access_token_expires_at: Date | null
  refresh_token_expires_at: Date | null
  scope: string | null
  password: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Real_estate_broker_system_accountCountAggregateOutputType = {
  id: number
  account_id: number
  provider_id: number
  user_id: number
  access_token: number
  refresh_token: number
  id_token: number
  access_token_expires_at: number
  refresh_token_expires_at: number
  scope: number
  password: number
  created_at: number
  updated_at: number
  _all: number
}


export type Real_estate_broker_system_accountMinAggregateInputType = {
  id?: true
  account_id?: true
  provider_id?: true
  user_id?: true
  access_token?: true
  refresh_token?: true
  id_token?: true
  access_token_expires_at?: true
  refresh_token_expires_at?: true
  scope?: true
  password?: true
  created_at?: true
  updated_at?: true
}

export type Real_estate_broker_system_accountMaxAggregateInputType = {
  id?: true
  account_id?: true
  provider_id?: true
  user_id?: true
  access_token?: true
  refresh_token?: true
  id_token?: true
  access_token_expires_at?: true
  refresh_token_expires_at?: true
  scope?: true
  password?: true
  created_at?: true
  updated_at?: true
}

export type Real_estate_broker_system_accountCountAggregateInputType = {
  id?: true
  account_id?: true
  provider_id?: true
  user_id?: true
  access_token?: true
  refresh_token?: true
  id_token?: true
  access_token_expires_at?: true
  refresh_token_expires_at?: true
  scope?: true
  password?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Real_estate_broker_system_accountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which real_estate_broker_system_account to aggregate.
   */
  where?: Prisma.real_estate_broker_system_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_accounts to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_accountOrderByWithRelationInput | Prisma.real_estate_broker_system_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.real_estate_broker_system_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned real_estate_broker_system_accounts
  **/
  _count?: true | Real_estate_broker_system_accountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Real_estate_broker_system_accountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Real_estate_broker_system_accountMaxAggregateInputType
}

export type GetReal_estate_broker_system_accountAggregateType<T extends Real_estate_broker_system_accountAggregateArgs> = {
      [P in keyof T & keyof AggregateReal_estate_broker_system_account]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReal_estate_broker_system_account[P]>
    : Prisma.GetScalarType<T[P], AggregateReal_estate_broker_system_account[P]>
}




export type real_estate_broker_system_accountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.real_estate_broker_system_accountWhereInput
  orderBy?: Prisma.real_estate_broker_system_accountOrderByWithAggregationInput | Prisma.real_estate_broker_system_accountOrderByWithAggregationInput[]
  by: Prisma.Real_estate_broker_system_accountScalarFieldEnum[] | Prisma.Real_estate_broker_system_accountScalarFieldEnum
  having?: Prisma.real_estate_broker_system_accountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Real_estate_broker_system_accountCountAggregateInputType | true
  _min?: Real_estate_broker_system_accountMinAggregateInputType
  _max?: Real_estate_broker_system_accountMaxAggregateInputType
}

export type Real_estate_broker_system_accountGroupByOutputType = {
  id: string
  account_id: string
  provider_id: string
  user_id: string
  access_token: string | null
  refresh_token: string | null
  id_token: string | null
  access_token_expires_at: Date | null
  refresh_token_expires_at: Date | null
  scope: string | null
  password: string | null
  created_at: Date
  updated_at: Date
  _count: Real_estate_broker_system_accountCountAggregateOutputType | null
  _min: Real_estate_broker_system_accountMinAggregateOutputType | null
  _max: Real_estate_broker_system_accountMaxAggregateOutputType | null
}

export type GetReal_estate_broker_system_accountGroupByPayload<T extends real_estate_broker_system_accountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Real_estate_broker_system_accountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Real_estate_broker_system_accountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Real_estate_broker_system_accountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Real_estate_broker_system_accountGroupByOutputType[P]>
      }
    >
  >



export type real_estate_broker_system_accountWhereInput = {
  AND?: Prisma.real_estate_broker_system_accountWhereInput | Prisma.real_estate_broker_system_accountWhereInput[]
  OR?: Prisma.real_estate_broker_system_accountWhereInput[]
  NOT?: Prisma.real_estate_broker_system_accountWhereInput | Prisma.real_estate_broker_system_accountWhereInput[]
  id?: Prisma.StringFilter<"real_estate_broker_system_account"> | string
  account_id?: Prisma.StringFilter<"real_estate_broker_system_account"> | string
  provider_id?: Prisma.StringFilter<"real_estate_broker_system_account"> | string
  user_id?: Prisma.StringFilter<"real_estate_broker_system_account"> | string
  access_token?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  refresh_token?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  id_token?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  access_token_expires_at?: Prisma.DateTimeNullableFilter<"real_estate_broker_system_account"> | Date | string | null
  refresh_token_expires_at?: Prisma.DateTimeNullableFilter<"real_estate_broker_system_account"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  password?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  created_at?: Prisma.DateTimeFilter<"real_estate_broker_system_account"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"real_estate_broker_system_account"> | Date | string
}

export type real_estate_broker_system_accountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token?: Prisma.SortOrderInput | Prisma.SortOrder
  id_token?: Prisma.SortOrderInput | Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type real_estate_broker_system_accountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.real_estate_broker_system_accountWhereInput | Prisma.real_estate_broker_system_accountWhereInput[]
  OR?: Prisma.real_estate_broker_system_accountWhereInput[]
  NOT?: Prisma.real_estate_broker_system_accountWhereInput | Prisma.real_estate_broker_system_accountWhereInput[]
  account_id?: Prisma.StringFilter<"real_estate_broker_system_account"> | string
  provider_id?: Prisma.StringFilter<"real_estate_broker_system_account"> | string
  user_id?: Prisma.StringFilter<"real_estate_broker_system_account"> | string
  access_token?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  refresh_token?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  id_token?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  access_token_expires_at?: Prisma.DateTimeNullableFilter<"real_estate_broker_system_account"> | Date | string | null
  refresh_token_expires_at?: Prisma.DateTimeNullableFilter<"real_estate_broker_system_account"> | Date | string | null
  scope?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  password?: Prisma.StringNullableFilter<"real_estate_broker_system_account"> | string | null
  created_at?: Prisma.DateTimeFilter<"real_estate_broker_system_account"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"real_estate_broker_system_account"> | Date | string
}, "id">

export type real_estate_broker_system_accountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token?: Prisma.SortOrderInput | Prisma.SortOrder
  id_token?: Prisma.SortOrderInput | Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.real_estate_broker_system_accountCountOrderByAggregateInput
  _max?: Prisma.real_estate_broker_system_accountMaxOrderByAggregateInput
  _min?: Prisma.real_estate_broker_system_accountMinOrderByAggregateInput
}

export type real_estate_broker_system_accountScalarWhereWithAggregatesInput = {
  AND?: Prisma.real_estate_broker_system_accountScalarWhereWithAggregatesInput | Prisma.real_estate_broker_system_accountScalarWhereWithAggregatesInput[]
  OR?: Prisma.real_estate_broker_system_accountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.real_estate_broker_system_accountScalarWhereWithAggregatesInput | Prisma.real_estate_broker_system_accountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"real_estate_broker_system_account"> | string
  account_id?: Prisma.StringWithAggregatesFilter<"real_estate_broker_system_account"> | string
  provider_id?: Prisma.StringWithAggregatesFilter<"real_estate_broker_system_account"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"real_estate_broker_system_account"> | string
  access_token?: Prisma.StringNullableWithAggregatesFilter<"real_estate_broker_system_account"> | string | null
  refresh_token?: Prisma.StringNullableWithAggregatesFilter<"real_estate_broker_system_account"> | string | null
  id_token?: Prisma.StringNullableWithAggregatesFilter<"real_estate_broker_system_account"> | string | null
  access_token_expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"real_estate_broker_system_account"> | Date | string | null
  refresh_token_expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"real_estate_broker_system_account"> | Date | string | null
  scope?: Prisma.StringNullableWithAggregatesFilter<"real_estate_broker_system_account"> | string | null
  password?: Prisma.StringNullableWithAggregatesFilter<"real_estate_broker_system_account"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"real_estate_broker_system_account"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"real_estate_broker_system_account"> | Date | string
}

export type real_estate_broker_system_accountCreateInput = {
  id: string
  account_id: string
  provider_id: string
  user_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type real_estate_broker_system_accountUncheckedCreateInput = {
  id: string
  account_id: string
  provider_id: string
  user_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type real_estate_broker_system_accountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type real_estate_broker_system_accountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type real_estate_broker_system_accountCreateManyInput = {
  id: string
  account_id: string
  provider_id: string
  user_id: string
  access_token?: string | null
  refresh_token?: string | null
  id_token?: string | null
  access_token_expires_at?: Date | string | null
  refresh_token_expires_at?: Date | string | null
  scope?: string | null
  password?: string | null
  created_at?: Date | string
  updated_at: Date | string
}

export type real_estate_broker_system_accountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type real_estate_broker_system_accountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  account_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  access_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  refresh_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  id_token?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  access_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  refresh_token_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type real_estate_broker_system_accountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrder
  refresh_token?: Prisma.SortOrder
  id_token?: Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  password?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type real_estate_broker_system_accountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrder
  refresh_token?: Prisma.SortOrder
  id_token?: Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  password?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type real_estate_broker_system_accountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  account_id?: Prisma.SortOrder
  provider_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  access_token?: Prisma.SortOrder
  refresh_token?: Prisma.SortOrder
  id_token?: Prisma.SortOrder
  access_token_expires_at?: Prisma.SortOrder
  refresh_token_expires_at?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  password?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}



export type real_estate_broker_system_accountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["real_estate_broker_system_account"]>

export type real_estate_broker_system_accountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["real_estate_broker_system_account"]>

export type real_estate_broker_system_accountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["real_estate_broker_system_account"]>

export type real_estate_broker_system_accountSelectScalar = {
  id?: boolean
  account_id?: boolean
  provider_id?: boolean
  user_id?: boolean
  access_token?: boolean
  refresh_token?: boolean
  id_token?: boolean
  access_token_expires_at?: boolean
  refresh_token_expires_at?: boolean
  scope?: boolean
  password?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type real_estate_broker_system_accountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "account_id" | "provider_id" | "user_id" | "access_token" | "refresh_token" | "id_token" | "access_token_expires_at" | "refresh_token_expires_at" | "scope" | "password" | "created_at" | "updated_at", ExtArgs["result"]["real_estate_broker_system_account"]>

export type $real_estate_broker_system_accountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "real_estate_broker_system_account"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    account_id: string
    provider_id: string
    user_id: string
    access_token: string | null
    refresh_token: string | null
    id_token: string | null
    access_token_expires_at: Date | null
    refresh_token_expires_at: Date | null
    scope: string | null
    password: string | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["real_estate_broker_system_account"]>
  composites: {}
}

export type real_estate_broker_system_accountGetPayload<S extends boolean | null | undefined | real_estate_broker_system_accountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload, S>

export type real_estate_broker_system_accountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<real_estate_broker_system_accountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Real_estate_broker_system_accountCountAggregateInputType | true
  }

export interface real_estate_broker_system_accountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['real_estate_broker_system_account'], meta: { name: 'real_estate_broker_system_account' } }
  /**
   * Find zero or one Real_estate_broker_system_account that matches the filter.
   * @param {real_estate_broker_system_accountFindUniqueArgs} args - Arguments to find a Real_estate_broker_system_account
   * @example
   * // Get one Real_estate_broker_system_account
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends real_estate_broker_system_accountFindUniqueArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Real_estate_broker_system_account that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {real_estate_broker_system_accountFindUniqueOrThrowArgs} args - Arguments to find a Real_estate_broker_system_account
   * @example
   * // Get one Real_estate_broker_system_account
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends real_estate_broker_system_accountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Real_estate_broker_system_account that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_accountFindFirstArgs} args - Arguments to find a Real_estate_broker_system_account
   * @example
   * // Get one Real_estate_broker_system_account
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends real_estate_broker_system_accountFindFirstArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_accountFindFirstArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Real_estate_broker_system_account that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_accountFindFirstOrThrowArgs} args - Arguments to find a Real_estate_broker_system_account
   * @example
   * // Get one Real_estate_broker_system_account
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends real_estate_broker_system_accountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_accountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Real_estate_broker_system_accounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_accountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Real_estate_broker_system_accounts
   * const real_estate_broker_system_accounts = await prisma.real_estate_broker_system_account.findMany()
   * 
   * // Get first 10 Real_estate_broker_system_accounts
   * const real_estate_broker_system_accounts = await prisma.real_estate_broker_system_account.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const real_estate_broker_system_accountWithIdOnly = await prisma.real_estate_broker_system_account.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends real_estate_broker_system_accountFindManyArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_accountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Real_estate_broker_system_account.
   * @param {real_estate_broker_system_accountCreateArgs} args - Arguments to create a Real_estate_broker_system_account.
   * @example
   * // Create one Real_estate_broker_system_account
   * const Real_estate_broker_system_account = await prisma.real_estate_broker_system_account.create({
   *   data: {
   *     // ... data to create a Real_estate_broker_system_account
   *   }
   * })
   * 
   */
  create<T extends real_estate_broker_system_accountCreateArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountCreateArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Real_estate_broker_system_accounts.
   * @param {real_estate_broker_system_accountCreateManyArgs} args - Arguments to create many Real_estate_broker_system_accounts.
   * @example
   * // Create many Real_estate_broker_system_accounts
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends real_estate_broker_system_accountCreateManyArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_accountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Real_estate_broker_system_accounts and returns the data saved in the database.
   * @param {real_estate_broker_system_accountCreateManyAndReturnArgs} args - Arguments to create many Real_estate_broker_system_accounts.
   * @example
   * // Create many Real_estate_broker_system_accounts
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Real_estate_broker_system_accounts and only return the `id`
   * const real_estate_broker_system_accountWithIdOnly = await prisma.real_estate_broker_system_account.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends real_estate_broker_system_accountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_accountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Real_estate_broker_system_account.
   * @param {real_estate_broker_system_accountDeleteArgs} args - Arguments to delete one Real_estate_broker_system_account.
   * @example
   * // Delete one Real_estate_broker_system_account
   * const Real_estate_broker_system_account = await prisma.real_estate_broker_system_account.delete({
   *   where: {
   *     // ... filter to delete one Real_estate_broker_system_account
   *   }
   * })
   * 
   */
  delete<T extends real_estate_broker_system_accountDeleteArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountDeleteArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Real_estate_broker_system_account.
   * @param {real_estate_broker_system_accountUpdateArgs} args - Arguments to update one Real_estate_broker_system_account.
   * @example
   * // Update one Real_estate_broker_system_account
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends real_estate_broker_system_accountUpdateArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountUpdateArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Real_estate_broker_system_accounts.
   * @param {real_estate_broker_system_accountDeleteManyArgs} args - Arguments to filter Real_estate_broker_system_accounts to delete.
   * @example
   * // Delete a few Real_estate_broker_system_accounts
   * const { count } = await prisma.real_estate_broker_system_account.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends real_estate_broker_system_accountDeleteManyArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_accountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Real_estate_broker_system_accounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_accountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Real_estate_broker_system_accounts
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends real_estate_broker_system_accountUpdateManyArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Real_estate_broker_system_accounts and returns the data updated in the database.
   * @param {real_estate_broker_system_accountUpdateManyAndReturnArgs} args - Arguments to update many Real_estate_broker_system_accounts.
   * @example
   * // Update many Real_estate_broker_system_accounts
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Real_estate_broker_system_accounts and only return the `id`
   * const real_estate_broker_system_accountWithIdOnly = await prisma.real_estate_broker_system_account.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends real_estate_broker_system_accountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Real_estate_broker_system_account.
   * @param {real_estate_broker_system_accountUpsertArgs} args - Arguments to update or create a Real_estate_broker_system_account.
   * @example
   * // Update or create a Real_estate_broker_system_account
   * const real_estate_broker_system_account = await prisma.real_estate_broker_system_account.upsert({
   *   create: {
   *     // ... data to create a Real_estate_broker_system_account
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Real_estate_broker_system_account we want to update
   *   }
   * })
   */
  upsert<T extends real_estate_broker_system_accountUpsertArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_accountUpsertArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_accountClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_accountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Real_estate_broker_system_accounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_accountCountArgs} args - Arguments to filter Real_estate_broker_system_accounts to count.
   * @example
   * // Count the number of Real_estate_broker_system_accounts
   * const count = await prisma.real_estate_broker_system_account.count({
   *   where: {
   *     // ... the filter for the Real_estate_broker_system_accounts we want to count
   *   }
   * })
  **/
  count<T extends real_estate_broker_system_accountCountArgs>(
    args?: Prisma.Subset<T, real_estate_broker_system_accountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Real_estate_broker_system_accountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Real_estate_broker_system_account.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Real_estate_broker_system_accountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Real_estate_broker_system_accountAggregateArgs>(args: Prisma.Subset<T, Real_estate_broker_system_accountAggregateArgs>): Prisma.PrismaPromise<GetReal_estate_broker_system_accountAggregateType<T>>

  /**
   * Group by Real_estate_broker_system_account.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_accountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends real_estate_broker_system_accountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: real_estate_broker_system_accountGroupByArgs['orderBy'] }
      : { orderBy?: real_estate_broker_system_accountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, real_estate_broker_system_accountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReal_estate_broker_system_accountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the real_estate_broker_system_account model
 */
readonly fields: real_estate_broker_system_accountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for real_estate_broker_system_account.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__real_estate_broker_system_accountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the real_estate_broker_system_account model
 */
export interface real_estate_broker_system_accountFieldRefs {
  readonly id: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly account_id: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly provider_id: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly user_id: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly access_token: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly refresh_token: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly id_token: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly access_token_expires_at: Prisma.FieldRef<"real_estate_broker_system_account", 'DateTime'>
  readonly refresh_token_expires_at: Prisma.FieldRef<"real_estate_broker_system_account", 'DateTime'>
  readonly scope: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly password: Prisma.FieldRef<"real_estate_broker_system_account", 'String'>
  readonly created_at: Prisma.FieldRef<"real_estate_broker_system_account", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"real_estate_broker_system_account", 'DateTime'>
}
    

// Custom InputTypes
/**
 * real_estate_broker_system_account findUnique
 */
export type real_estate_broker_system_accountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_account to fetch.
   */
  where: Prisma.real_estate_broker_system_accountWhereUniqueInput
}

/**
 * real_estate_broker_system_account findUniqueOrThrow
 */
export type real_estate_broker_system_accountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_account to fetch.
   */
  where: Prisma.real_estate_broker_system_accountWhereUniqueInput
}

/**
 * real_estate_broker_system_account findFirst
 */
export type real_estate_broker_system_accountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_account to fetch.
   */
  where?: Prisma.real_estate_broker_system_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_accounts to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_accountOrderByWithRelationInput | Prisma.real_estate_broker_system_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for real_estate_broker_system_accounts.
   */
  cursor?: Prisma.real_estate_broker_system_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of real_estate_broker_system_accounts.
   */
  distinct?: Prisma.Real_estate_broker_system_accountScalarFieldEnum | Prisma.Real_estate_broker_system_accountScalarFieldEnum[]
}

/**
 * real_estate_broker_system_account findFirstOrThrow
 */
export type real_estate_broker_system_accountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_account to fetch.
   */
  where?: Prisma.real_estate_broker_system_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_accounts to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_accountOrderByWithRelationInput | Prisma.real_estate_broker_system_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for real_estate_broker_system_accounts.
   */
  cursor?: Prisma.real_estate_broker_system_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of real_estate_broker_system_accounts.
   */
  distinct?: Prisma.Real_estate_broker_system_accountScalarFieldEnum | Prisma.Real_estate_broker_system_accountScalarFieldEnum[]
}

/**
 * real_estate_broker_system_account findMany
 */
export type real_estate_broker_system_accountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_accounts to fetch.
   */
  where?: Prisma.real_estate_broker_system_accountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_accounts to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_accountOrderByWithRelationInput | Prisma.real_estate_broker_system_accountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing real_estate_broker_system_accounts.
   */
  cursor?: Prisma.real_estate_broker_system_accountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_accounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_accounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of real_estate_broker_system_accounts.
   */
  distinct?: Prisma.Real_estate_broker_system_accountScalarFieldEnum | Prisma.Real_estate_broker_system_accountScalarFieldEnum[]
}

/**
 * real_estate_broker_system_account create
 */
export type real_estate_broker_system_accountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * The data needed to create a real_estate_broker_system_account.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_accountCreateInput, Prisma.real_estate_broker_system_accountUncheckedCreateInput>
}

/**
 * real_estate_broker_system_account createMany
 */
export type real_estate_broker_system_accountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many real_estate_broker_system_accounts.
   */
  data: Prisma.real_estate_broker_system_accountCreateManyInput | Prisma.real_estate_broker_system_accountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * real_estate_broker_system_account createManyAndReturn
 */
export type real_estate_broker_system_accountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * The data used to create many real_estate_broker_system_accounts.
   */
  data: Prisma.real_estate_broker_system_accountCreateManyInput | Prisma.real_estate_broker_system_accountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * real_estate_broker_system_account update
 */
export type real_estate_broker_system_accountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * The data needed to update a real_estate_broker_system_account.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_accountUpdateInput, Prisma.real_estate_broker_system_accountUncheckedUpdateInput>
  /**
   * Choose, which real_estate_broker_system_account to update.
   */
  where: Prisma.real_estate_broker_system_accountWhereUniqueInput
}

/**
 * real_estate_broker_system_account updateMany
 */
export type real_estate_broker_system_accountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update real_estate_broker_system_accounts.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_accountUpdateManyMutationInput, Prisma.real_estate_broker_system_accountUncheckedUpdateManyInput>
  /**
   * Filter which real_estate_broker_system_accounts to update
   */
  where?: Prisma.real_estate_broker_system_accountWhereInput
  /**
   * Limit how many real_estate_broker_system_accounts to update.
   */
  limit?: number
}

/**
 * real_estate_broker_system_account updateManyAndReturn
 */
export type real_estate_broker_system_accountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * The data used to update real_estate_broker_system_accounts.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_accountUpdateManyMutationInput, Prisma.real_estate_broker_system_accountUncheckedUpdateManyInput>
  /**
   * Filter which real_estate_broker_system_accounts to update
   */
  where?: Prisma.real_estate_broker_system_accountWhereInput
  /**
   * Limit how many real_estate_broker_system_accounts to update.
   */
  limit?: number
}

/**
 * real_estate_broker_system_account upsert
 */
export type real_estate_broker_system_accountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * The filter to search for the real_estate_broker_system_account to update in case it exists.
   */
  where: Prisma.real_estate_broker_system_accountWhereUniqueInput
  /**
   * In case the real_estate_broker_system_account found by the `where` argument doesn't exist, create a new real_estate_broker_system_account with this data.
   */
  create: Prisma.XOR<Prisma.real_estate_broker_system_accountCreateInput, Prisma.real_estate_broker_system_accountUncheckedCreateInput>
  /**
   * In case the real_estate_broker_system_account was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.real_estate_broker_system_accountUpdateInput, Prisma.real_estate_broker_system_accountUncheckedUpdateInput>
}

/**
 * real_estate_broker_system_account delete
 */
export type real_estate_broker_system_accountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
  /**
   * Filter which real_estate_broker_system_account to delete.
   */
  where: Prisma.real_estate_broker_system_accountWhereUniqueInput
}

/**
 * real_estate_broker_system_account deleteMany
 */
export type real_estate_broker_system_accountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which real_estate_broker_system_accounts to delete
   */
  where?: Prisma.real_estate_broker_system_accountWhereInput
  /**
   * Limit how many real_estate_broker_system_accounts to delete.
   */
  limit?: number
}

/**
 * real_estate_broker_system_account without action
 */
export type real_estate_broker_system_accountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_account
   */
  select?: Prisma.real_estate_broker_system_accountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_account
   */
  omit?: Prisma.real_estate_broker_system_accountOmit<ExtArgs> | null
}
