
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `real_estate_broker_system_session` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model real_estate_broker_system_session
 * 
 */
export type real_estate_broker_system_sessionModel = runtime.Types.Result.DefaultSelection<Prisma.$real_estate_broker_system_sessionPayload>

export type AggregateReal_estate_broker_system_session = {
  _count: Real_estate_broker_system_sessionCountAggregateOutputType | null
  _min: Real_estate_broker_system_sessionMinAggregateOutputType | null
  _max: Real_estate_broker_system_sessionMaxAggregateOutputType | null
}

export type Real_estate_broker_system_sessionMinAggregateOutputType = {
  id: string | null
  expires_at: Date | null
  token: string | null
  created_at: Date | null
  updated_at: Date | null
  ip_address: string | null
  user_agent: string | null
  user_id: string | null
}

export type Real_estate_broker_system_sessionMaxAggregateOutputType = {
  id: string | null
  expires_at: Date | null
  token: string | null
  created_at: Date | null
  updated_at: Date | null
  ip_address: string | null
  user_agent: string | null
  user_id: string | null
}

export type Real_estate_broker_system_sessionCountAggregateOutputType = {
  id: number
  expires_at: number
  token: number
  created_at: number
  updated_at: number
  ip_address: number
  user_agent: number
  user_id: number
  _all: number
}


export type Real_estate_broker_system_sessionMinAggregateInputType = {
  id?: true
  expires_at?: true
  token?: true
  created_at?: true
  updated_at?: true
  ip_address?: true
  user_agent?: true
  user_id?: true
}

export type Real_estate_broker_system_sessionMaxAggregateInputType = {
  id?: true
  expires_at?: true
  token?: true
  created_at?: true
  updated_at?: true
  ip_address?: true
  user_agent?: true
  user_id?: true
}

export type Real_estate_broker_system_sessionCountAggregateInputType = {
  id?: true
  expires_at?: true
  token?: true
  created_at?: true
  updated_at?: true
  ip_address?: true
  user_agent?: true
  user_id?: true
  _all?: true
}

export type Real_estate_broker_system_sessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which real_estate_broker_system_session to aggregate.
   */
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_sessions to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_sessionOrderByWithRelationInput | Prisma.real_estate_broker_system_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.real_estate_broker_system_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned real_estate_broker_system_sessions
  **/
  _count?: true | Real_estate_broker_system_sessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Real_estate_broker_system_sessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Real_estate_broker_system_sessionMaxAggregateInputType
}

export type GetReal_estate_broker_system_sessionAggregateType<T extends Real_estate_broker_system_sessionAggregateArgs> = {
      [P in keyof T & keyof AggregateReal_estate_broker_system_session]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReal_estate_broker_system_session[P]>
    : Prisma.GetScalarType<T[P], AggregateReal_estate_broker_system_session[P]>
}




export type real_estate_broker_system_sessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  orderBy?: Prisma.real_estate_broker_system_sessionOrderByWithAggregationInput | Prisma.real_estate_broker_system_sessionOrderByWithAggregationInput[]
  by: Prisma.Real_estate_broker_system_sessionScalarFieldEnum[] | Prisma.Real_estate_broker_system_sessionScalarFieldEnum
  having?: Prisma.real_estate_broker_system_sessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Real_estate_broker_system_sessionCountAggregateInputType | true
  _min?: Real_estate_broker_system_sessionMinAggregateInputType
  _max?: Real_estate_broker_system_sessionMaxAggregateInputType
}

export type Real_estate_broker_system_sessionGroupByOutputType = {
  id: string
  expires_at: Date
  token: string
  created_at: Date
  updated_at: Date
  ip_address: string | null
  user_agent: string | null
  user_id: string
  _count: Real_estate_broker_system_sessionCountAggregateOutputType | null
  _min: Real_estate_broker_system_sessionMinAggregateOutputType | null
  _max: Real_estate_broker_system_sessionMaxAggregateOutputType | null
}

export type GetReal_estate_broker_system_sessionGroupByPayload<T extends real_estate_broker_system_sessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Real_estate_broker_system_sessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Real_estate_broker_system_sessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Real_estate_broker_system_sessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Real_estate_broker_system_sessionGroupByOutputType[P]>
      }
    >
  >



export type real_estate_broker_system_sessionWhereInput = {
  AND?: Prisma.real_estate_broker_system_sessionWhereInput | Prisma.real_estate_broker_system_sessionWhereInput[]
  OR?: Prisma.real_estate_broker_system_sessionWhereInput[]
  NOT?: Prisma.real_estate_broker_system_sessionWhereInput | Prisma.real_estate_broker_system_sessionWhereInput[]
  id?: Prisma.StringFilter<"real_estate_broker_system_session"> | string
  expires_at?: Prisma.DateTimeFilter<"real_estate_broker_system_session"> | Date | string
  token?: Prisma.StringFilter<"real_estate_broker_system_session"> | string
  created_at?: Prisma.DateTimeFilter<"real_estate_broker_system_session"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"real_estate_broker_system_session"> | Date | string
  ip_address?: Prisma.StringNullableFilter<"real_estate_broker_system_session"> | string | null
  user_agent?: Prisma.StringNullableFilter<"real_estate_broker_system_session"> | string | null
  user_id?: Prisma.StringFilter<"real_estate_broker_system_session"> | string
}

export type real_estate_broker_system_sessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  token?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  ip_address?: Prisma.SortOrderInput | Prisma.SortOrder
  user_agent?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type real_estate_broker_system_sessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  token?: string
  AND?: Prisma.real_estate_broker_system_sessionWhereInput | Prisma.real_estate_broker_system_sessionWhereInput[]
  OR?: Prisma.real_estate_broker_system_sessionWhereInput[]
  NOT?: Prisma.real_estate_broker_system_sessionWhereInput | Prisma.real_estate_broker_system_sessionWhereInput[]
  expires_at?: Prisma.DateTimeFilter<"real_estate_broker_system_session"> | Date | string
  created_at?: Prisma.DateTimeFilter<"real_estate_broker_system_session"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"real_estate_broker_system_session"> | Date | string
  ip_address?: Prisma.StringNullableFilter<"real_estate_broker_system_session"> | string | null
  user_agent?: Prisma.StringNullableFilter<"real_estate_broker_system_session"> | string | null
  user_id?: Prisma.StringFilter<"real_estate_broker_system_session"> | string
}, "id" | "token">

export type real_estate_broker_system_sessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  token?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  ip_address?: Prisma.SortOrderInput | Prisma.SortOrder
  user_agent?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrder
  _count?: Prisma.real_estate_broker_system_sessionCountOrderByAggregateInput
  _max?: Prisma.real_estate_broker_system_sessionMaxOrderByAggregateInput
  _min?: Prisma.real_estate_broker_system_sessionMinOrderByAggregateInput
}

export type real_estate_broker_system_sessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.real_estate_broker_system_sessionScalarWhereWithAggregatesInput | Prisma.real_estate_broker_system_sessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.real_estate_broker_system_sessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.real_estate_broker_system_sessionScalarWhereWithAggregatesInput | Prisma.real_estate_broker_system_sessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"real_estate_broker_system_session"> | string
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"real_estate_broker_system_session"> | Date | string
  token?: Prisma.StringWithAggregatesFilter<"real_estate_broker_system_session"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"real_estate_broker_system_session"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"real_estate_broker_system_session"> | Date | string
  ip_address?: Prisma.StringNullableWithAggregatesFilter<"real_estate_broker_system_session"> | string | null
  user_agent?: Prisma.StringNullableWithAggregatesFilter<"real_estate_broker_system_session"> | string | null
  user_id?: Prisma.StringWithAggregatesFilter<"real_estate_broker_system_session"> | string
}

export type real_estate_broker_system_sessionCreateInput = {
  id: string
  expires_at: Date | string
  token: string
  created_at?: Date | string
  updated_at: Date | string
  ip_address?: string | null
  user_agent?: string | null
  user_id: string
}

export type real_estate_broker_system_sessionUncheckedCreateInput = {
  id: string
  expires_at: Date | string
  token: string
  created_at?: Date | string
  updated_at: Date | string
  ip_address?: string | null
  user_agent?: string | null
  user_id: string
}

export type real_estate_broker_system_sessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type real_estate_broker_system_sessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type real_estate_broker_system_sessionCreateManyInput = {
  id: string
  expires_at: Date | string
  token: string
  created_at?: Date | string
  updated_at: Date | string
  ip_address?: string | null
  user_agent?: string | null
  user_id: string
}

export type real_estate_broker_system_sessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type real_estate_broker_system_sessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ip_address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_agent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type real_estate_broker_system_sessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  token?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  user_agent?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type real_estate_broker_system_sessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  token?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  user_agent?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type real_estate_broker_system_sessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  token?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  user_agent?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}



export type real_estate_broker_system_sessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  expires_at?: boolean
  token?: boolean
  created_at?: boolean
  updated_at?: boolean
  ip_address?: boolean
  user_agent?: boolean
  user_id?: boolean
}, ExtArgs["result"]["real_estate_broker_system_session"]>

export type real_estate_broker_system_sessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  expires_at?: boolean
  token?: boolean
  created_at?: boolean
  updated_at?: boolean
  ip_address?: boolean
  user_agent?: boolean
  user_id?: boolean
}, ExtArgs["result"]["real_estate_broker_system_session"]>

export type real_estate_broker_system_sessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  expires_at?: boolean
  token?: boolean
  created_at?: boolean
  updated_at?: boolean
  ip_address?: boolean
  user_agent?: boolean
  user_id?: boolean
}, ExtArgs["result"]["real_estate_broker_system_session"]>

export type real_estate_broker_system_sessionSelectScalar = {
  id?: boolean
  expires_at?: boolean
  token?: boolean
  created_at?: boolean
  updated_at?: boolean
  ip_address?: boolean
  user_agent?: boolean
  user_id?: boolean
}

export type real_estate_broker_system_sessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "expires_at" | "token" | "created_at" | "updated_at" | "ip_address" | "user_agent" | "user_id", ExtArgs["result"]["real_estate_broker_system_session"]>

export type $real_estate_broker_system_sessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "real_estate_broker_system_session"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    expires_at: Date
    token: string
    created_at: Date
    updated_at: Date
    ip_address: string | null
    user_agent: string | null
    user_id: string
  }, ExtArgs["result"]["real_estate_broker_system_session"]>
  composites: {}
}

export type real_estate_broker_system_sessionGetPayload<S extends boolean | null | undefined | real_estate_broker_system_sessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload, S>

export type real_estate_broker_system_sessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<real_estate_broker_system_sessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Real_estate_broker_system_sessionCountAggregateInputType | true
  }

export interface real_estate_broker_system_sessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['real_estate_broker_system_session'], meta: { name: 'real_estate_broker_system_session' } }
  /**
   * Find zero or one Real_estate_broker_system_session that matches the filter.
   * @param {real_estate_broker_system_sessionFindUniqueArgs} args - Arguments to find a Real_estate_broker_system_session
   * @example
   * // Get one Real_estate_broker_system_session
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends real_estate_broker_system_sessionFindUniqueArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Real_estate_broker_system_session that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {real_estate_broker_system_sessionFindUniqueOrThrowArgs} args - Arguments to find a Real_estate_broker_system_session
   * @example
   * // Get one Real_estate_broker_system_session
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends real_estate_broker_system_sessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Real_estate_broker_system_session that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_sessionFindFirstArgs} args - Arguments to find a Real_estate_broker_system_session
   * @example
   * // Get one Real_estate_broker_system_session
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends real_estate_broker_system_sessionFindFirstArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_sessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Real_estate_broker_system_session that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_sessionFindFirstOrThrowArgs} args - Arguments to find a Real_estate_broker_system_session
   * @example
   * // Get one Real_estate_broker_system_session
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends real_estate_broker_system_sessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_sessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Real_estate_broker_system_sessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_sessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Real_estate_broker_system_sessions
   * const real_estate_broker_system_sessions = await prisma.real_estate_broker_system_session.findMany()
   * 
   * // Get first 10 Real_estate_broker_system_sessions
   * const real_estate_broker_system_sessions = await prisma.real_estate_broker_system_session.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const real_estate_broker_system_sessionWithIdOnly = await prisma.real_estate_broker_system_session.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends real_estate_broker_system_sessionFindManyArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_sessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Real_estate_broker_system_session.
   * @param {real_estate_broker_system_sessionCreateArgs} args - Arguments to create a Real_estate_broker_system_session.
   * @example
   * // Create one Real_estate_broker_system_session
   * const Real_estate_broker_system_session = await prisma.real_estate_broker_system_session.create({
   *   data: {
   *     // ... data to create a Real_estate_broker_system_session
   *   }
   * })
   * 
   */
  create<T extends real_estate_broker_system_sessionCreateArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionCreateArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Real_estate_broker_system_sessions.
   * @param {real_estate_broker_system_sessionCreateManyArgs} args - Arguments to create many Real_estate_broker_system_sessions.
   * @example
   * // Create many Real_estate_broker_system_sessions
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends real_estate_broker_system_sessionCreateManyArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_sessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Real_estate_broker_system_sessions and returns the data saved in the database.
   * @param {real_estate_broker_system_sessionCreateManyAndReturnArgs} args - Arguments to create many Real_estate_broker_system_sessions.
   * @example
   * // Create many Real_estate_broker_system_sessions
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Real_estate_broker_system_sessions and only return the `id`
   * const real_estate_broker_system_sessionWithIdOnly = await prisma.real_estate_broker_system_session.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends real_estate_broker_system_sessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_sessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Real_estate_broker_system_session.
   * @param {real_estate_broker_system_sessionDeleteArgs} args - Arguments to delete one Real_estate_broker_system_session.
   * @example
   * // Delete one Real_estate_broker_system_session
   * const Real_estate_broker_system_session = await prisma.real_estate_broker_system_session.delete({
   *   where: {
   *     // ... filter to delete one Real_estate_broker_system_session
   *   }
   * })
   * 
   */
  delete<T extends real_estate_broker_system_sessionDeleteArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionDeleteArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Real_estate_broker_system_session.
   * @param {real_estate_broker_system_sessionUpdateArgs} args - Arguments to update one Real_estate_broker_system_session.
   * @example
   * // Update one Real_estate_broker_system_session
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends real_estate_broker_system_sessionUpdateArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionUpdateArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Real_estate_broker_system_sessions.
   * @param {real_estate_broker_system_sessionDeleteManyArgs} args - Arguments to filter Real_estate_broker_system_sessions to delete.
   * @example
   * // Delete a few Real_estate_broker_system_sessions
   * const { count } = await prisma.real_estate_broker_system_session.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends real_estate_broker_system_sessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, real_estate_broker_system_sessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Real_estate_broker_system_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_sessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Real_estate_broker_system_sessions
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends real_estate_broker_system_sessionUpdateManyArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Real_estate_broker_system_sessions and returns the data updated in the database.
   * @param {real_estate_broker_system_sessionUpdateManyAndReturnArgs} args - Arguments to update many Real_estate_broker_system_sessions.
   * @example
   * // Update many Real_estate_broker_system_sessions
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Real_estate_broker_system_sessions and only return the `id`
   * const real_estate_broker_system_sessionWithIdOnly = await prisma.real_estate_broker_system_session.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends real_estate_broker_system_sessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Real_estate_broker_system_session.
   * @param {real_estate_broker_system_sessionUpsertArgs} args - Arguments to update or create a Real_estate_broker_system_session.
   * @example
   * // Update or create a Real_estate_broker_system_session
   * const real_estate_broker_system_session = await prisma.real_estate_broker_system_session.upsert({
   *   create: {
   *     // ... data to create a Real_estate_broker_system_session
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Real_estate_broker_system_session we want to update
   *   }
   * })
   */
  upsert<T extends real_estate_broker_system_sessionUpsertArgs>(args: Prisma.SelectSubset<T, real_estate_broker_system_sessionUpsertArgs<ExtArgs>>): Prisma.Prisma__real_estate_broker_system_sessionClient<runtime.Types.Result.GetResult<Prisma.$real_estate_broker_system_sessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Real_estate_broker_system_sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_sessionCountArgs} args - Arguments to filter Real_estate_broker_system_sessions to count.
   * @example
   * // Count the number of Real_estate_broker_system_sessions
   * const count = await prisma.real_estate_broker_system_session.count({
   *   where: {
   *     // ... the filter for the Real_estate_broker_system_sessions we want to count
   *   }
   * })
  **/
  count<T extends real_estate_broker_system_sessionCountArgs>(
    args?: Prisma.Subset<T, real_estate_broker_system_sessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Real_estate_broker_system_sessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Real_estate_broker_system_session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Real_estate_broker_system_sessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Real_estate_broker_system_sessionAggregateArgs>(args: Prisma.Subset<T, Real_estate_broker_system_sessionAggregateArgs>): Prisma.PrismaPromise<GetReal_estate_broker_system_sessionAggregateType<T>>

  /**
   * Group by Real_estate_broker_system_session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {real_estate_broker_system_sessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends real_estate_broker_system_sessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: real_estate_broker_system_sessionGroupByArgs['orderBy'] }
      : { orderBy?: real_estate_broker_system_sessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, real_estate_broker_system_sessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReal_estate_broker_system_sessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the real_estate_broker_system_session model
 */
readonly fields: real_estate_broker_system_sessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for real_estate_broker_system_session.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__real_estate_broker_system_sessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the real_estate_broker_system_session model
 */
export interface real_estate_broker_system_sessionFieldRefs {
  readonly id: Prisma.FieldRef<"real_estate_broker_system_session", 'String'>
  readonly expires_at: Prisma.FieldRef<"real_estate_broker_system_session", 'DateTime'>
  readonly token: Prisma.FieldRef<"real_estate_broker_system_session", 'String'>
  readonly created_at: Prisma.FieldRef<"real_estate_broker_system_session", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"real_estate_broker_system_session", 'DateTime'>
  readonly ip_address: Prisma.FieldRef<"real_estate_broker_system_session", 'String'>
  readonly user_agent: Prisma.FieldRef<"real_estate_broker_system_session", 'String'>
  readonly user_id: Prisma.FieldRef<"real_estate_broker_system_session", 'String'>
}
    

// Custom InputTypes
/**
 * real_estate_broker_system_session findUnique
 */
export type real_estate_broker_system_sessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_session to fetch.
   */
  where: Prisma.real_estate_broker_system_sessionWhereUniqueInput
}

/**
 * real_estate_broker_system_session findUniqueOrThrow
 */
export type real_estate_broker_system_sessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_session to fetch.
   */
  where: Prisma.real_estate_broker_system_sessionWhereUniqueInput
}

/**
 * real_estate_broker_system_session findFirst
 */
export type real_estate_broker_system_sessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_session to fetch.
   */
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_sessions to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_sessionOrderByWithRelationInput | Prisma.real_estate_broker_system_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for real_estate_broker_system_sessions.
   */
  cursor?: Prisma.real_estate_broker_system_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of real_estate_broker_system_sessions.
   */
  distinct?: Prisma.Real_estate_broker_system_sessionScalarFieldEnum | Prisma.Real_estate_broker_system_sessionScalarFieldEnum[]
}

/**
 * real_estate_broker_system_session findFirstOrThrow
 */
export type real_estate_broker_system_sessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_session to fetch.
   */
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_sessions to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_sessionOrderByWithRelationInput | Prisma.real_estate_broker_system_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for real_estate_broker_system_sessions.
   */
  cursor?: Prisma.real_estate_broker_system_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of real_estate_broker_system_sessions.
   */
  distinct?: Prisma.Real_estate_broker_system_sessionScalarFieldEnum | Prisma.Real_estate_broker_system_sessionScalarFieldEnum[]
}

/**
 * real_estate_broker_system_session findMany
 */
export type real_estate_broker_system_sessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * Filter, which real_estate_broker_system_sessions to fetch.
   */
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of real_estate_broker_system_sessions to fetch.
   */
  orderBy?: Prisma.real_estate_broker_system_sessionOrderByWithRelationInput | Prisma.real_estate_broker_system_sessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing real_estate_broker_system_sessions.
   */
  cursor?: Prisma.real_estate_broker_system_sessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` real_estate_broker_system_sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` real_estate_broker_system_sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of real_estate_broker_system_sessions.
   */
  distinct?: Prisma.Real_estate_broker_system_sessionScalarFieldEnum | Prisma.Real_estate_broker_system_sessionScalarFieldEnum[]
}

/**
 * real_estate_broker_system_session create
 */
export type real_estate_broker_system_sessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * The data needed to create a real_estate_broker_system_session.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_sessionCreateInput, Prisma.real_estate_broker_system_sessionUncheckedCreateInput>
}

/**
 * real_estate_broker_system_session createMany
 */
export type real_estate_broker_system_sessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many real_estate_broker_system_sessions.
   */
  data: Prisma.real_estate_broker_system_sessionCreateManyInput | Prisma.real_estate_broker_system_sessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * real_estate_broker_system_session createManyAndReturn
 */
export type real_estate_broker_system_sessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * The data used to create many real_estate_broker_system_sessions.
   */
  data: Prisma.real_estate_broker_system_sessionCreateManyInput | Prisma.real_estate_broker_system_sessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * real_estate_broker_system_session update
 */
export type real_estate_broker_system_sessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * The data needed to update a real_estate_broker_system_session.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_sessionUpdateInput, Prisma.real_estate_broker_system_sessionUncheckedUpdateInput>
  /**
   * Choose, which real_estate_broker_system_session to update.
   */
  where: Prisma.real_estate_broker_system_sessionWhereUniqueInput
}

/**
 * real_estate_broker_system_session updateMany
 */
export type real_estate_broker_system_sessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update real_estate_broker_system_sessions.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_sessionUpdateManyMutationInput, Prisma.real_estate_broker_system_sessionUncheckedUpdateManyInput>
  /**
   * Filter which real_estate_broker_system_sessions to update
   */
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  /**
   * Limit how many real_estate_broker_system_sessions to update.
   */
  limit?: number
}

/**
 * real_estate_broker_system_session updateManyAndReturn
 */
export type real_estate_broker_system_sessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * The data used to update real_estate_broker_system_sessions.
   */
  data: Prisma.XOR<Prisma.real_estate_broker_system_sessionUpdateManyMutationInput, Prisma.real_estate_broker_system_sessionUncheckedUpdateManyInput>
  /**
   * Filter which real_estate_broker_system_sessions to update
   */
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  /**
   * Limit how many real_estate_broker_system_sessions to update.
   */
  limit?: number
}

/**
 * real_estate_broker_system_session upsert
 */
export type real_estate_broker_system_sessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * The filter to search for the real_estate_broker_system_session to update in case it exists.
   */
  where: Prisma.real_estate_broker_system_sessionWhereUniqueInput
  /**
   * In case the real_estate_broker_system_session found by the `where` argument doesn't exist, create a new real_estate_broker_system_session with this data.
   */
  create: Prisma.XOR<Prisma.real_estate_broker_system_sessionCreateInput, Prisma.real_estate_broker_system_sessionUncheckedCreateInput>
  /**
   * In case the real_estate_broker_system_session was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.real_estate_broker_system_sessionUpdateInput, Prisma.real_estate_broker_system_sessionUncheckedUpdateInput>
}

/**
 * real_estate_broker_system_session delete
 */
export type real_estate_broker_system_sessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
  /**
   * Filter which real_estate_broker_system_session to delete.
   */
  where: Prisma.real_estate_broker_system_sessionWhereUniqueInput
}

/**
 * real_estate_broker_system_session deleteMany
 */
export type real_estate_broker_system_sessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which real_estate_broker_system_sessions to delete
   */
  where?: Prisma.real_estate_broker_system_sessionWhereInput
  /**
   * Limit how many real_estate_broker_system_sessions to delete.
   */
  limit?: number
}

/**
 * real_estate_broker_system_session without action
 */
export type real_estate_broker_system_sessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the real_estate_broker_system_session
   */
  select?: Prisma.real_estate_broker_system_sessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the real_estate_broker_system_session
   */
  omit?: Prisma.real_estate_broker_system_sessionOmit<ExtArgs> | null
}
